- INFO - 2021-04-05 14:43:54,445 - Init Server
- INFO - 2021-04-05 14:44:16,877 - access_token is expired. Now: 2021-04-05 07:44:16.877786, token_expiry: 2021-04-01 08:59:01
- INFO - 2021-04-05 14:44:16,884 - access_token is expired. Now: 2021-04-05 07:44:16.884787, token_expiry: 2021-04-01 08:59:01
- INFO - 2021-04-05 14:45:00,958 - Init Server
- INFO - 2021-04-05 14:45:23,430 - access_token is expired. Now: 2021-04-05 07:45:23.430466, token_expiry: 2021-04-01 08:59:01
- INFO - 2021-04-05 14:45:23,430 - access_token is expired. Now: 2021-04-05 07:45:23.430466, token_expiry: 2021-04-01 08:59:01
- INFO - 2021-04-05 14:45:27,677 - Received token response with no refresh_token. Consider reauthenticating with prompt='consent'.
- INFO - 2021-04-05 14:45:27,678 - Successfully retrieved access token
- INFO - 2021-04-05 14:45:27,742 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-04-05 14:45:29,942 - upload_file -> (file_name: test2, file_content: content 2)
- INFO - 2021-04-05 14:46:14,236 - upload_file -> (file_name: test, file_content: content 2)
- INFO - 2021-04-05 14:48:42,809 - get_files_by_title -> (title: test)
- INFO - 2021-04-05 14:49:11,823 - get_files_by_title -> (title: test)
- INFO - 2021-04-05 14:50:13,128 - get_content_file -> (file : 1n8qrUC7ZTyE9Ne1-vmnA05NT4q_3hh17 - test)
- INFO - 2021-04-05 15:11:19,713 - upload_file -> (file_name: test 3, file_content: content 2)
- INFO - 2021-04-05 15:13:07,909 - Init Server
- INFO - 2021-04-05 15:13:12,435 - access_token is expired. Now: 2021-04-05 08:13:12.435929, token_expiry: 2021-04-01 08:59:01
- INFO - 2021-04-05 15:13:12,442 - access_token is expired. Now: 2021-04-05 08:13:12.442930, token_expiry: 2021-04-01 08:59:01
- INFO - 2021-04-05 15:13:16,982 - Received token response with no refresh_token. Consider reauthenticating with prompt='consent'.
- INFO - 2021-04-05 15:13:16,983 - Successfully retrieved access token
- INFO - 2021-04-05 15:13:17,072 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-04-05 15:13:18,362 - get_files_by_title -> (title: test)
- INFO - 2021-04-05 15:13:46,650 - get_content_file -> (file : 1n8qrUC7ZTyE9Ne1-vmnA05NT4q_3hh17 - test)
- INFO - 2021-04-05 15:13:50,419 - get_content_file -> (file : 1yJac2YjlUT3LN2cu9yEpLOfzcF9hKkil - test)
- INFO - 2021-04-05 15:18:58,668 - Init Server
- INFO - 2021-04-05 15:19:08,011 - access_token is expired. Now: 2021-04-05 08:19:08.011736, token_expiry: 2021-04-01 08:59:01
- INFO - 2021-04-05 15:19:08,027 - access_token is expired. Now: 2021-04-05 08:19:08.027336, token_expiry: 2021-04-01 08:59:01
- INFO - 2021-04-05 15:19:54,396 - Init Server
- INFO - 2021-04-05 15:20:06,936 - access_token is expired. Now: 2021-04-05 08:20:06.936843, token_expiry: 2021-04-01 08:59:01
- INFO - 2021-04-05 15:20:06,943 - access_token is expired. Now: 2021-04-05 08:20:06.943843, token_expiry: 2021-04-01 08:59:01
- INFO - 2021-04-05 15:20:11,755 - Received token response with no refresh_token. Consider reauthenticating with prompt='consent'.
- INFO - 2021-04-05 15:20:11,755 - Successfully retrieved access token
- INFO - 2021-04-05 15:20:11,833 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-04-05 15:20:12,763 - get_files_by_title -> (title: test)
- INFO - 2021-04-05 15:20:17,544 - get_files_by_title -> (title: test)
- INFO - 2021-04-05 15:20:41,805 - get_content_file -> (file : 1n8qrUC7ZTyE9Ne1-vmnA05NT4q_3hh17 - test)
- INFO - 2021-04-05 15:21:12,143 - get_file_by_id -> (file_id: 1n8qrUC7ZTyE9Ne1-vmnA05NT4q_3hh17)
- INFO - 2021-04-05 15:21:59,528 - Init Server
- INFO - 2021-04-05 15:22:14,690 - access_token is expired. Now: 2021-04-05 08:22:14.690266, token_expiry: 2021-04-01 08:59:01
- INFO - 2021-04-05 15:22:14,697 - access_token is expired. Now: 2021-04-05 08:22:14.697267, token_expiry: 2021-04-01 08:59:01
- INFO - 2021-04-05 15:22:18,165 - Received token response with no refresh_token. Consider reauthenticating with prompt='consent'.
- INFO - 2021-04-05 15:22:18,165 - Successfully retrieved access token
- INFO - 2021-04-05 15:22:18,281 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-04-05 15:22:18,999 - get_files_by_title -> (title: test)
- INFO - 2021-04-05 15:23:15,355 - get_file_by_id -> (file_id: 1n8qrUC7ZTyE9Ne1-vmnA05NT4q_3hh17)
- INFO - 2021-04-05 15:23:16,587 - delete_file_by_id -> (file_id: 1n8qrUC7ZTyE9Ne1-vmnA05NT4q_3hh17)
- INFO - 2021-04-23 20:57:18,617 - D:\GitHub\secure-file-storage-app\api\file_manager\file_storage\file_storage.py changed, reloading.
- INFO - 2021-04-23 21:04:59,165 - D:\GitHub\secure-file-storage-app\api\file_manager\file_storage\file_storage.py changed, reloading.
- INFO - 2021-04-24 13:08:59,400 - Init Server
- INFO - 2021-04-24 13:08:59,427 - access_token is expired. Now: 2021-04-24 06:08:59.427114, token_expiry: 2021-04-23 14:45:19
- INFO - 2021-04-24 13:08:59,449 - access_token is expired. Now: 2021-04-24 06:08:59.449116, token_expiry: 2021-04-23 14:45:19
- INFO - 2021-04-24 13:09:03,079 - Received token response with no refresh_token. Consider reauthenticating with prompt='consent'.
- INFO - 2021-04-24 13:09:03,079 - Successfully retrieved access token
- INFO - 2021-04-24 13:09:03,243 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-04-24 13:09:05,614 - upload_file -> (file_name: Statistics_StateDiagram.png)
- INFO - 2021-04-24 13:10:13,378 - Init Server
- INFO - 2021-04-24 13:10:13,384 - access_token is expired. Now: 2021-04-24 06:10:13.384344, token_expiry: 2021-04-23 14:45:19
- INFO - 2021-04-24 13:10:13,391 - access_token is expired. Now: 2021-04-24 06:10:13.391345, token_expiry: 2021-04-23 14:45:19
- INFO - 2021-04-24 13:10:14,250 - Received token response with no refresh_token. Consider reauthenticating with prompt='consent'.
- INFO - 2021-04-24 13:10:14,250 - Successfully retrieved access token
- INFO - 2021-04-24 13:10:14,328 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-04-24 13:10:16,724 - upload_file -> (file_name: girl_xinh.jpg)
- INFO - 2021-04-24 14:30:38,227 - D:\GitHub\secure-file-storage-app\api\file_manager\file_storage\file_storage.py changed, reloading.
- INFO - 2021-04-24 14:32:25,336 - Init Server
- INFO - 2021-04-24 14:33:01,673 - access_token is expired. Now: 2021-04-24 07:33:01.673686, token_expiry: 2021-04-23 14:45:19
- INFO - 2021-04-24 14:33:01,674 - access_token is expired. Now: 2021-04-24 07:33:01.674686, token_expiry: 2021-04-23 14:45:19
- INFO - 2021-04-24 14:34:00,793 - Init Server
- INFO - 2021-04-24 14:34:09,480 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-04-24 14:34:11,016 - get_file_list
- INFO - 2021-04-24 14:34:29,214 - get_file_list
- INFO - 2021-04-24 14:35:56,406 - get_files_by_title -> (title: download (2).png)
- INFO - 2021-04-24 14:37:19,936 - get_content_file -> (file : 1_oFafQUOGbszJGMP0sw7eNMzgbpltUjL - download (2).png)
- ERROR - 2021-04-24 18:07:59,635 - Internal Server Error: /api/test
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 426, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
- INFO - 2021-04-24 18:09:31,184 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-04-24 18:21:12,704 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-04-24 18:21:46,816 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- ERROR - 2021-04-24 18:27:05,583 - Internal Server Error: /api/test
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py", line 61, in post
    if serializer.is_valid():
  File "C:\Python37\lib\site-packages\rest_framework\serializers.py", line 220, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "C:\Python37\lib\site-packages\rest_framework\serializers.py", line 419, in run_validation
    value = self.to_internal_value(data)
  File "C:\Python37\lib\site-packages\rest_framework\serializers.py", line 472, in to_internal_value
    for field in fields:
  File "C:\Python37\lib\site-packages\rest_framework\serializers.py", line 355, in _writable_fields
    for field in self.fields.values():
  File "C:\Python37\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Python37\lib\site-packages\rest_framework\serializers.py", line 349, in fields
    for key, value in self.get_fields().items():
  File "C:\Python37\lib\site-packages\rest_framework\serializers.py", line 1006, in get_fields
    serializer_class=self.__class__.__name__
AssertionError: Class FileUploadSerializer missing "Meta" attribute
- INFO - 2021-04-24 18:27:16,573 - D:\GitHub\secure-file-storage-app\api\file_manager\file\serializers.py changed, reloading.
- WARNING - 2021-04-24 18:38:31,651 - Method Not Allowed: /api/test
- WARNING - 2021-04-24 18:38:38,866 - Bad Request: /api/test
- WARNING - 2021-04-24 18:39:28,240 - Bad Request: /api/test
- WARNING - 2021-04-24 18:40:05,898 - Bad Request: /api/test
- WARNING - 2021-04-24 18:40:38,803 - Bad Request: /api/test
- WARNING - 2021-04-24 18:41:48,305 - Bad Request: /api/test
- INFO - 2021-04-24 18:44:32,720 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-04-24 18:45:02,710 - Init Server
- INFO - 2021-04-24 18:45:02,772 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-04-24 18:45:04,867 - upload_file -> (file_name: requirements.txt)
- WARNING - 2021-04-24 18:45:41,325 - Bad Request: /api/file
- INFO - 2021-04-24 18:47:11,443 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-04-24 18:54:48,826 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-04-24 18:55:16,802 - D:\GitHub\secure-file-storage-app\api\file_manager\file\urls.py changed, reloading.
- INFO - 2021-04-24 18:57:33,710 - D:\GitHub\secure-file-storage-app\api\file_manager\file\urls.py changed, reloading.
- WARNING - 2021-04-24 18:57:52,081 - Method Not Allowed: /api/test
- WARNING - 2021-04-24 18:57:58,988 - Not Found: /api/test/�
- ERROR - 2021-04-24 18:58:06,249 - Internal Server Error: /api/test/123
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: get() got an unexpected keyword argument 'file_id'
- INFO - 2021-04-24 18:59:32,432 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- ERROR - 2021-04-24 19:00:02,110 - Internal Server Error: /api/test/123
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py", line 66, in get
    print(args)
NameError: name 'arg' is not defined
- INFO - 2021-04-24 19:00:13,458 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-04-24 19:01:39,629 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-04-24 19:03:28,458 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-04-24 19:06:23,394 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-04-24 19:07:26,354 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-04-24 19:08:01,355 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-04-24 19:08:49,315 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-04-24 19:09:21,512 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-04-24 19:11:22,273 - Init Server
- INFO - 2021-04-24 19:11:22,348 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-04-24 19:11:23,110 - get_files_by_title -> (title: map.json)
- ERROR - 2021-04-24 19:11:23,309 - Internal Server Error: /api/test/123
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py", line 70, in get
    if len(FileUploadSerializer) == 0:
TypeError: object of type 'SerializerMetaclass' has no len()
- INFO - 2021-04-24 19:11:35,642 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-04-24 19:12:07,842 - Init Server
- INFO - 2021-04-24 19:12:07,912 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-04-24 19:12:08,496 - get_files_by_title -> (title: map.json)
- INFO - 2021-04-24 19:12:08,497 - get_content_file -> (file : 1r-4t6DsmI89FDjHQdK4oEIYtRFkJxXv7 - map.json)
- INFO - 2021-04-24 19:12:11,575 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-04-24 19:21:16,382 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-04-24 19:21:49,048 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-04-24 19:23:06,765 - Init Server
- INFO - 2021-04-24 19:23:06,851 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-04-24 19:23:07,590 - get_files_by_title -> (title: map.json)
- INFO - 2021-04-24 19:23:07,590 - get_content_file -> (file : 1r-4t6DsmI89FDjHQdK4oEIYtRFkJxXv7 - map.json)
- INFO - 2021-04-24 19:23:16,698 - Init Server
- INFO - 2021-04-24 19:23:16,701 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-04-24 19:23:17,273 - get_files_by_title -> (title: map.json)
- INFO - 2021-04-24 19:23:17,274 - get_content_file -> (file : 1r-4t6DsmI89FDjHQdK4oEIYtRFkJxXv7 - map.json)
- INFO - 2021-04-24 19:23:30,228 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-04-24 19:28:17,981 - Init Server
- INFO - 2021-04-24 19:28:18,057 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-04-24 19:28:18,668 - get_files_by_title -> (title: map.json)
- INFO - 2021-04-24 19:28:18,669 - get_content_file -> (file : 1r-4t6DsmI89FDjHQdK4oEIYtRFkJxXv7 - map.json)
- INFO - 2021-04-24 19:28:26,179 - Init Server
- INFO - 2021-04-24 19:28:26,182 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-04-24 19:28:26,682 - get_files_by_title -> (title: map.json)
- INFO - 2021-04-24 19:28:26,682 - get_content_file -> (file : 1r-4t6DsmI89FDjHQdK4oEIYtRFkJxXv7 - map.json)
- INFO - 2021-04-24 19:29:56,306 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-04-24 19:30:26,647 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-04-24 19:31:11,298 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-04-24 19:37:01,880 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-04-24 19:37:25,563 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-04-24 19:37:57,155 - Init Server
- INFO - 2021-04-24 19:37:57,242 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-04-24 19:37:57,887 - get_files_by_title -> (title: map.json)
- INFO - 2021-04-24 19:37:57,887 - get_content_file -> (file : 1r-4t6DsmI89FDjHQdK4oEIYtRFkJxXv7 - map.json)
- INFO - 2021-04-24 19:37:59,382 - get_files_by_title -> (title: 000007private_key.txt.aes)
- ERROR - 2021-04-24 19:37:59,643 - Internal Server Error: /api/test/007
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py", line 91, in get
    file_storage.download_file(files[0], base_dir + file_name)
TypeError: download_file() missing 1 required positional argument: 'file_path'
- INFO - 2021-04-24 19:38:22,724 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-04-24 19:38:43,480 - Init Server
- INFO - 2021-04-24 19:38:43,554 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-04-24 19:38:44,202 - get_files_by_title -> (title: map.json)
- INFO - 2021-04-24 19:38:44,202 - get_content_file -> (file : 1r-4t6DsmI89FDjHQdK4oEIYtRFkJxXv7 - map.json)
- INFO - 2021-04-24 19:38:45,721 - get_files_by_title -> (title: 000007private_key.txt.aes)
- INFO - 2021-04-24 19:38:46,889 - download_file -> (file_name: .temp/000007private_key.txt.aes)
- INFO - 2021-04-24 19:47:33,354 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-04-24 20:34:58,742 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-04-24 20:36:59,379 - Init Server
- INFO - 2021-04-24 20:36:59,426 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-04-24 20:37:00,058 - get_files_by_title -> (title: map.json)
- INFO - 2021-04-24 20:37:00,058 - get_content_file -> (file : 1r-4t6DsmI89FDjHQdK4oEIYtRFkJxXv7 - map.json)
- INFO - 2021-04-24 20:37:01,939 - get_files_by_title -> (title: 000007private_key.txt.aes)
- INFO - 2021-04-24 20:37:03,201 - download_file -> (file_name: .temp/000007private_key.txt.aes)
- WARNING - 2021-04-24 21:12:54,103 - Not Found: /api/file/0007
- INFO - 2021-04-24 21:13:19,041 - Init Server
- INFO - 2021-04-24 21:13:19,103 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-04-24 21:13:19,879 - get_files_by_title -> (title: map.json)
- INFO - 2021-04-24 21:13:19,879 - get_content_file -> (file : 1r-4t6DsmI89FDjHQdK4oEIYtRFkJxXv7 - map.json)
- INFO - 2021-04-24 21:13:21,628 - get_files_by_title -> (title: 000007private_key.txt.aes)
- INFO - 2021-04-24 21:13:22,874 - download_file -> (file_name: .temp/000007private_key.txt.aes)
- INFO - 2021-04-24 21:15:16,278 - Init Server
- INFO - 2021-04-24 21:15:16,306 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-04-24 21:15:17,022 - get_files_by_title -> (title: map.json)
- INFO - 2021-04-24 21:15:17,022 - get_content_file -> (file : 1r-4t6DsmI89FDjHQdK4oEIYtRFkJxXv7 - map.json)
- INFO - 2021-04-24 21:15:18,552 - get_files_by_title -> (title: 000007private_key.txt.aes)
- INFO - 2021-04-24 21:15:19,701 - download_file -> (file_name: .temp/000007private_key.txt.aes)
- INFO - 2021-04-24 21:16:24,132 - Init Server
- INFO - 2021-04-24 21:16:24,159 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-04-24 21:16:24,678 - get_files_by_title -> (title: map.json)
- INFO - 2021-04-24 21:16:24,679 - get_content_file -> (file : 1r-4t6DsmI89FDjHQdK4oEIYtRFkJxXv7 - map.json)
- INFO - 2021-04-24 21:16:26,370 - get_files_by_title -> (title: 000007private_key.txt.aes)
- INFO - 2021-04-24 21:16:27,469 - download_file -> (file_name: .temp/000007private_key.txt.aes)
- INFO - 2021-04-24 21:21:01,368 - D:\GitHub\secure-file-storage-app\api\file_manager\file\urls.py changed, reloading.
- WARNING - 2021-04-25 00:02:46,031 - Bad Request: /api/login
- WARNING - 2021-04-25 00:04:17,371 - Bad Request: /api/login
- WARNING - 2021-04-25 00:05:51,288 - Bad Request: /api/login
- WARNING - 2021-04-25 00:05:57,817 - Bad Request: /api/login
- WARNING - 2021-04-25 00:06:04,295 - Bad Request: /api/login
- WARNING - 2021-04-25 00:11:13,009 - Bad Request: /api/login
- WARNING - 2021-04-25 00:11:28,350 - Bad Request: /api/login
- WARNING - 2021-04-25 00:15:01,646 - Bad Request: /api/login
- WARNING - 2021-04-25 00:15:19,167 - Bad Request: /api/login
- WARNING - 2021-04-25 00:15:24,304 - Bad Request: /api/login
- WARNING - 2021-04-25 00:15:29,408 - Bad Request: /api/login
- INFO - 2021-04-25 00:16:24,586 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- WARNING - 2021-04-25 00:17:04,510 - Bad Request: /api/login
- WARNING - 2021-04-25 00:17:40,069 - Bad Request: /api/login
- WARNING - 2021-04-25 00:19:04,101 - Bad Request: /api/login
- WARNING - 2021-04-25 00:20:09,873 - Bad Request: /api/login
- WARNING - 2021-04-25 00:20:14,041 - Bad Request: /api/login
- WARNING - 2021-04-25 00:21:14,038 - Bad Request: /api/login
- WARNING - 2021-04-25 00:21:27,748 - Bad Request: /api/login
- WARNING - 2021-04-25 11:38:17,945 - Not Found: /api/testauth
- WARNING - 2021-04-25 11:38:29,037 - Forbidden: /api/test_auth
- INFO - 2021-04-25 11:40:39,279 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- WARNING - 2021-04-25 11:41:00,447 - Forbidden: /api/test_auth
- INFO - 2021-04-25 11:41:08,985 - D:\GitHub\secure-file-storage-app\api\file_manager\user\urls.py changed, reloading.
- WARNING - 2021-04-25 11:41:24,014 - Forbidden: /api/test_auth
- INFO - 2021-04-25 12:20:17,166 - D:\GitHub\secure-file-storage-app\api\file_manager\file_manager\settings.py changed, reloading.
- WARNING - 2021-04-25 12:20:53,093 - Forbidden: /api/test_auth
- INFO - 2021-04-25 12:21:00,497 - D:\GitHub\secure-file-storage-app\api\file_manager\file_manager\settings.py changed, reloading.
- INFO - 2021-04-25 12:23:53,982 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- WARNING - 2021-04-25 12:50:57,399 - Forbidden: /api/test_auth
- WARNING - 2021-04-25 12:58:48,791 - Forbidden: /api/test_auth
- WARNING - 2021-04-25 12:59:23,132 - Forbidden: /api/test_auth
- WARNING - 2021-04-25 13:00:39,787 - Forbidden: /api/test_auth
- WARNING - 2021-04-25 13:02:26,889 - Not Found: /
- WARNING - 2021-04-25 13:02:27,286 - Not Found: /favicon.ico
- INFO - 2021-04-25 13:05:37,805 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- INFO - 2021-04-25 13:09:05,047 - D:\GitHub\secure-file-storage-app\api\file_manager\file_manager\settings.py changed, reloading.
- WARNING - 2021-04-25 13:09:48,582 - Unauthorized: /api/test_auth
- WARNING - 2021-04-25 13:10:04,897 - Unauthorized: /api/test_auth
- INFO - 2021-04-25 13:13:43,748 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- ERROR - 2021-04-25 13:15:01,148 - Internal Server Error: /api/test_auth
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Python37\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Python37\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Python37\lib\site-packages\rest_framework\renderers.py", line 103, in render
    allow_nan=not self.strict, separators=separators
  File "C:\Python37\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Python37\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type User is not JSON serializable
- INFO - 2021-04-25 13:15:37,379 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- INFO - 2021-04-25 13:17:12,076 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- ERROR - 2021-04-25 13:17:36,100 - Internal Server Error: /api/test_auth
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Python37\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Python37\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Python37\lib\site-packages\rest_framework\renderers.py", line 103, in render
    allow_nan=not self.strict, separators=separators
  File "C:\Python37\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Python37\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type User is not JSON serializable
- INFO - 2021-04-25 13:17:50,794 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- INFO - 2021-04-25 13:21:04,868 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- INFO - 2021-04-25 13:26:13,452 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- INFO - 2021-04-25 13:26:34,236 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- INFO - 2021-04-25 13:27:01,808 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- ERROR - 2021-04-25 13:27:23,576 - Internal Server Error: /api/test_auth
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py", line 70, in post
    serialized_user = serializers.serialize('json', [ request.user, ])
AttributeError: module 'rest_framework.serializers' has no attribute 'serialize'
- INFO - 2021-04-25 13:28:19,152 - D:\GitHub\secure-file-storage-app\api\file_manager\user\serializers.py changed, reloading.
- ERROR - 2021-04-25 13:28:50,646 - Internal Server Error: /api/test_auth
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py", line 70, in post
    print(serialized_user)
AttributeError: module 'rest_framework.serializers' has no attribute 'serialize'
- INFO - 2021-04-25 13:28:52,465 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- INFO - 2021-04-25 13:30:09,416 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- INFO - 2021-04-25 14:50:06,980 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- WARNING - 2021-04-25 15:13:10,979 - Bad Request: /api/login
- WARNING - 2021-04-25 15:13:18,944 - Bad Request: /api/login
- WARNING - 2021-04-25 15:13:26,732 - Bad Request: /api/login
- WARNING - 2021-04-25 15:13:42,891 - Bad Request: /api/login
- WARNING - 2021-04-25 15:14:15,513 - Bad Request: /api/login
- WARNING - 2021-04-25 15:17:44,887 - Bad Request: /api/login
- WARNING - 2021-04-25 15:19:48,433 - Bad Request: /api/login
- WARNING - 2021-04-25 15:22:59,269 - Bad Request: /api/login
- WARNING - 2021-04-25 15:23:00,760 - Bad Request: /api/login
- WARNING - 2021-04-28 13:15:15,803 - Unauthorized: /api/user
- WARNING - 2021-04-28 13:17:02,519 - Unauthorized: /api/user
- WARNING - 2021-04-28 13:17:42,881 - Unauthorized: /api/user
- WARNING - 2021-04-28 13:18:39,371 - Unauthorized: /api/user
- WARNING - 2021-04-28 13:19:29,739 - Unauthorized: /api/user
- WARNING - 2021-04-28 13:20:16,981 - Unauthorized: /api/user
- WARNING - 2021-04-28 13:21:21,576 - Unauthorized: /api/user
- WARNING - 2021-04-28 13:22:18,740 - Not Found: /
- WARNING - 2021-04-28 13:22:19,085 - Not Found: /favicon.ico
- WARNING - 2021-04-28 14:06:10,187 - Unauthorized: /api/user
- WARNING - 2021-04-28 14:37:31,120 - Unauthorized: /api/user
- WARNING - 2021-05-02 10:25:07,767 - Not Found: /favicon.ico
- WARNING - 2021-05-02 10:36:21,663 - Not Found: /
- WARNING - 2021-05-02 10:40:56,503 - Not Found: /
- WARNING - 2021-05-02 10:41:27,033 - Not Found: /favicon.ico
- WARNING - 2021-05-02 10:42:01,673 - Unauthorized: /api/user
- WARNING - 2021-05-02 10:44:36,224 - Unauthorized: /api/user
- WARNING - 2021-05-02 10:46:32,970 - Unauthorized: /api/user
- WARNING - 2021-05-02 10:48:07,420 - Unauthorized: /api/user
- WARNING - 2021-05-02 10:49:06,867 - Unauthorized: /api/user
- WARNING - 2021-05-02 10:49:45,881 - Unauthorized: /api/user
- WARNING - 2021-05-02 10:50:20,030 - Bad Request: /api/register
- WARNING - 2021-05-02 10:51:33,062 - Unauthorized: /api/user
- WARNING - 2021-05-02 11:05:52,067 - Bad Request: /api/register
- WARNING - 2021-05-02 11:06:33,512 - Bad Request: /api/register
- WARNING - 2021-05-02 11:06:41,778 - Bad Request: /api/register
- INFO - 2021-05-02 11:07:05,012 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- WARNING - 2021-05-02 11:08:36,770 - Bad Request: /api/register
- WARNING - 2021-05-02 11:08:59,757 - Bad Request: /api/login
- WARNING - 2021-05-02 12:56:05,934 - Unauthorized: /api/user
- WARNING - 2021-05-02 13:04:05,728 - Unauthorized: /api/user
- WARNING - 2021-05-02 13:05:56,627 - Unauthorized: /api/user
- WARNING - 2021-05-02 13:17:16,359 - Unauthorized: /api/user
- WARNING - 2021-05-02 13:24:05,680 - Unauthorized: /api/user
- WARNING - 2021-05-02 13:24:33,417 - Unauthorized: /api/user
- WARNING - 2021-05-02 13:26:04,957 - Unauthorized: /api/user
- WARNING - 2021-05-02 13:28:01,909 - Unauthorized: /api/user
- WARNING - 2021-05-02 13:31:33,471 - Unauthorized: /api/user
- WARNING - 2021-05-02 13:33:53,890 - Unauthorized: /api/user
- WARNING - 2021-05-02 13:37:45,721 - Unauthorized: /api/user
- WARNING - 2021-05-02 13:41:06,556 - Unauthorized: /api/user
- WARNING - 2021-05-02 13:47:15,494 - Unauthorized: /api/user
- WARNING - 2021-05-02 13:53:10,397 - Unauthorized: /api/user
- WARNING - 2021-05-02 13:59:31,870 - Unauthorized: /api/user
- WARNING - 2021-05-02 14:00:44,999 - Unauthorized: /api/user
- WARNING - 2021-05-02 14:09:37,559 - Unauthorized: /api/user
- WARNING - 2021-05-02 15:35:11,543 - Unauthorized: /api/user
- WARNING - 2021-05-02 15:36:26,760 - Unauthorized: /api/user
- WARNING - 2021-05-02 15:36:32,126 - Unauthorized: /api/user
- WARNING - 2021-05-02 15:36:39,277 - Unauthorized: /api/user
- WARNING - 2021-05-02 15:37:05,309 - Unauthorized: /api/user
- WARNING - 2021-05-02 15:37:29,191 - Unauthorized: /api/user
- WARNING - 2021-05-02 15:52:01,188 - Unauthorized: /api/user
- WARNING - 2021-05-02 15:54:22,382 - Unauthorized: /api/user
- WARNING - 2021-05-02 15:57:23,090 - Unauthorized: /api/user
- WARNING - 2021-05-02 15:59:25,633 - Unauthorized: /api/user
- WARNING - 2021-05-02 16:00:56,276 - Unauthorized: /api/user
- WARNING - 2021-05-02 16:02:34,009 - Unauthorized: /api/user
- WARNING - 2021-05-02 16:04:02,513 - Unauthorized: /api/user
- WARNING - 2021-05-02 16:05:20,623 - Unauthorized: /api/user
- WARNING - 2021-05-02 16:06:35,250 - Unauthorized: /api/user
- WARNING - 2021-05-02 16:07:42,791 - Unauthorized: /api/user
- WARNING - 2021-05-02 16:09:21,490 - Unauthorized: /api/user
- WARNING - 2021-05-02 16:15:30,075 - Unauthorized: /api/user
- WARNING - 2021-05-02 16:15:39,652 - Unauthorized: /api/user
- WARNING - 2021-05-02 16:18:54,070 - Unauthorized: /api/user
- WARNING - 2021-05-02 16:25:25,854 - Unauthorized: /api/user
- WARNING - 2021-05-02 16:45:52,651 - Unauthorized: /api/user
- WARNING - 2021-05-02 16:52:27,997 - Bad Request: /api/login
- WARNING - 2021-05-02 16:54:06,247 - Unauthorized: /api/user
- WARNING - 2021-05-02 17:12:15,709 - Bad Request: /api/login
- INFO - 2021-05-02 17:38:27,555 - D:\GitHub\secure-file-storage-app\api\file_manager\file_manager\settings.py changed, reloading.
- WARNING - 2021-05-02 17:41:10,387 - Not Found: /
- INFO - 2021-05-02 17:41:21,464 - D:\GitHub\secure-file-storage-app\api\file_manager\file_manager\urls.py changed, reloading.
- WARNING - 2021-05-02 17:41:53,529 - Not Found: /
- WARNING - 2021-05-02 17:41:59,024 - Not Found: /account
- WARNING - 2021-05-02 17:42:01,043 - Not Found: /accounts
- WARNING - 2021-05-02 17:42:05,121 - Not Found: /accounts/
- ERROR - 2021-05-02 17:47:36,910 - Internal Server Error: /accounts/password_reset
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\utils\deprecation.py", line 116, in __call__
    response = self.process_request(request)
  File "C:\Python37\lib\site-packages\django\middleware\common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "C:\Python37\lib\site-packages\django\middleware\common.py", line 95, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/accounts/password_reset/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
- ERROR - 2021-05-02 17:47:56,442 - Internal Server Error: /accounts/password_reset
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\utils\deprecation.py", line 116, in __call__
    response = self.process_request(request)
  File "C:\Python37\lib\site-packages\django\middleware\common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "C:\Python37\lib\site-packages\django\middleware\common.py", line 95, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/accounts/password_reset/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
- ERROR - 2021-05-02 17:49:14,235 - Internal Server Error: /accounts/password_reset
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\utils\deprecation.py", line 116, in __call__
    response = self.process_request(request)
  File "C:\Python37\lib\site-packages\django\middleware\common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "C:\Python37\lib\site-packages\django\middleware\common.py", line 95, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/accounts/password_reset/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
- ERROR - 2021-05-02 17:49:30,958 - Internal Server Error: /accounts/password_reset
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\utils\deprecation.py", line 116, in __call__
    response = self.process_request(request)
  File "C:\Python37\lib\site-packages\django\middleware\common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "C:\Python37\lib\site-packages\django\middleware\common.py", line 95, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/accounts/password_reset/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
- INFO - 2021-05-02 18:48:13,496 - D:\GitHub\secure-file-storage-app\api\file_manager\user\models.py changed, reloading.
- INFO - 2021-05-02 18:50:54,595 - D:\GitHub\secure-file-storage-app\api\file_manager\user\models.py changed, reloading.
- INFO - 2021-05-02 18:52:28,182 - D:\GitHub\secure-file-storage-app\api\file_manager\user\models.py changed, reloading.
- INFO - 2021-05-02 18:55:33,328 - D:\GitHub\secure-file-storage-app\api\file_manager\user\models.py changed, reloading.
- INFO - 2021-05-02 19:00:33,205 - D:\GitHub\secure-file-storage-app\api\file_manager\user\models.py changed, reloading.
- WARNING - 2021-05-02 19:02:46,582 - Unauthorized: /api/user
- INFO - 2021-05-02 19:04:04,857 - D:\GitHub\secure-file-storage-app\api\file_manager\user\serializers.py changed, reloading.
- INFO - 2021-05-02 19:05:38,175 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- INFO - 2021-05-02 19:06:39,840 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- ERROR - 2021-05-02 19:19:45,722 - Internal Server Error: /api/login
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Python37\lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: user_userhistory.email

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py", line 57, in post
    user_history.save()
  File "C:\Python37\lib\site-packages\django\db\models\base.py", line 727, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Python37\lib\site-packages\django\db\models\base.py", line 765, in save_base
    force_update, using, update_fields,
  File "C:\Python37\lib\site-packages\django\db\models\base.py", line 868, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "C:\Python37\lib\site-packages\django\db\models\base.py", line 908, in _do_insert
    using=using, raw=raw,
  File "C:\Python37\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\db\models\query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Python37\lib\site-packages\django\db\models\sql\compiler.py", line 1410, in execute_sql
    cursor.execute(sql, params)
  File "C:\Python37\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "C:\Python37\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Python37\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Python37\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Python37\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Python37\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Python37\lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: user_userhistory.email
- INFO - 2021-05-02 19:21:00,344 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- INFO - 2021-05-02 19:22:20,332 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- ERROR - 2021-05-02 19:22:37,820 - Internal Server Error: /api/login
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Python37\lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: user_userhistory.email

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py", line 64, in post
    user_history.save()
  File "C:\Python37\lib\site-packages\django\db\models\base.py", line 727, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Python37\lib\site-packages\django\db\models\base.py", line 765, in save_base
    force_update, using, update_fields,
  File "C:\Python37\lib\site-packages\django\db\models\base.py", line 868, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "C:\Python37\lib\site-packages\django\db\models\base.py", line 908, in _do_insert
    using=using, raw=raw,
  File "C:\Python37\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\db\models\query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Python37\lib\site-packages\django\db\models\sql\compiler.py", line 1410, in execute_sql
    cursor.execute(sql, params)
  File "C:\Python37\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "C:\Python37\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Python37\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Python37\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Python37\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Python37\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Python37\lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: user_userhistory.email
- INFO - 2021-05-02 19:24:14,480 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- ERROR - 2021-05-02 19:24:35,546 - Internal Server Error: /api/login
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Python37\lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: user_userhistory.email

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py", line 62, in post
    user_history.save()
  File "C:\Python37\lib\site-packages\django\db\models\base.py", line 727, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Python37\lib\site-packages\django\db\models\base.py", line 765, in save_base
    force_update, using, update_fields,
  File "C:\Python37\lib\site-packages\django\db\models\base.py", line 868, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "C:\Python37\lib\site-packages\django\db\models\base.py", line 908, in _do_insert
    using=using, raw=raw,
  File "C:\Python37\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\db\models\query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Python37\lib\site-packages\django\db\models\sql\compiler.py", line 1410, in execute_sql
    cursor.execute(sql, params)
  File "C:\Python37\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "C:\Python37\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Python37\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Python37\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Python37\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Python37\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Python37\lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: user_userhistory.email
- INFO - 2021-05-02 19:27:38,040 - D:\GitHub\secure-file-storage-app\api\file_manager\user\admin.py changed, reloading.
- INFO - 2021-05-02 19:31:35,404 - D:\GitHub\secure-file-storage-app\api\file_manager\user\admin.py changed, reloading.
- INFO - 2021-05-02 19:32:09,140 - D:\GitHub\secure-file-storage-app\api\file_manager\user\admin.py changed, reloading.
- WARNING - 2021-05-02 19:39:10,526 - Bad Request: /api/login
- WARNING - 2021-05-02 19:39:14,459 - Bad Request: /api/login
- WARNING - 2021-05-02 20:46:12,882 - Bad Request: /api/login
- INFO - 2021-05-02 20:47:17,231 - D:\GitHub\secure-file-storage-app\api\file_manager\user\serializers.py changed, reloading.
- INFO - 2021-05-02 20:48:04,585 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- WARNING - 2021-05-02 20:48:25,737 - Bad Request: /api/login
- INFO - 2021-05-02 20:48:41,072 - D:\GitHub\secure-file-storage-app\api\file_manager\user\serializers.py changed, reloading.
- WARNING - 2021-05-02 20:49:43,421 - Unauthorized: /api/login_history
- WARNING - 2021-05-02 20:50:06,171 - Method Not Allowed: /api/login_history
- ERROR - 2021-05-02 20:50:24,639 - Internal Server Error: /api/login_history
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py", line 99, in get
    for user_history in UserHistory.objects.get(email = email):
TypeError: 'UserHistory' object is not iterable
- INFO - 2021-05-02 20:57:25,380 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- WARNING - 2021-05-02 21:20:44,076 - Unauthorized: /api/user
- WARNING - 2021-05-02 21:24:19,665 - Unauthorized: /api/user
- WARNING - 2021-05-02 21:24:19,675 - Unauthorized: /api/login_history
- WARNING - 2021-05-02 21:27:00,199 - Unauthorized: /api/user
- WARNING - 2021-05-02 21:27:00,203 - Unauthorized: /api/login_history
- WARNING - 2021-05-02 21:27:46,437 - Unauthorized: /api/login_history
- WARNING - 2021-05-02 21:28:02,331 - Bad Request: /api/login
- WARNING - 2021-05-02 21:28:05,565 - Bad Request: /api/login
- WARNING - 2021-05-02 22:28:10,231 - Unauthorized: /api/user
- WARNING - 2021-05-02 22:28:10,235 - Unauthorized: /api/login_history
- WARNING - 2021-05-02 22:37:09,900 - Unauthorized: /api/user
- WARNING - 2021-05-02 22:37:09,905 - Unauthorized: /api/login_history
- WARNING - 2021-05-02 22:39:00,828 - Bad Request: /api/login
- WARNING - 2021-05-02 22:39:15,937 - Bad Request: /api/login
- WARNING - 2021-05-02 22:39:25,398 - Bad Request: /api/login
- WARNING - 2021-05-02 23:18:47,664 - Unauthorized: /api/user
- WARNING - 2021-05-02 23:18:47,727 - Unauthorized: /api/login_history
- WARNING - 2021-05-02 23:18:59,439 - Unauthorized: /api/user
- WARNING - 2021-05-02 23:18:59,445 - Unauthorized: /api/login_history
- WARNING - 2021-05-02 23:19:41,619 - Unauthorized: /api/user
- WARNING - 2021-05-02 23:19:41,631 - Unauthorized: /api/login_history
- WARNING - 2021-05-02 23:20:28,069 - Unauthorized: /api/login_history
- WARNING - 2021-05-02 23:20:28,070 - Unauthorized: /api/user
- WARNING - 2021-05-02 23:23:54,741 - Unauthorized: /api/user
- WARNING - 2021-05-02 23:23:54,746 - Unauthorized: /api/login_history
- WARNING - 2021-05-02 23:28:01,500 - Unauthorized: /api/user
- WARNING - 2021-05-02 23:28:01,526 - Unauthorized: /api/login_history
- WARNING - 2021-05-02 23:37:56,471 - Unauthorized: /api/user
- WARNING - 2021-05-02 23:37:56,476 - Unauthorized: /api/login_history
- WARNING - 2021-05-02 23:38:11,194 - Unauthorized: /api/user
- WARNING - 2021-05-02 23:38:11,197 - Unauthorized: /api/login_history
- WARNING - 2021-05-02 23:39:10,897 - Unauthorized: /api/user
- WARNING - 2021-05-02 23:39:10,902 - Unauthorized: /api/login_history
- WARNING - 2021-05-02 23:45:47,518 - Unauthorized: /api/user
- WARNING - 2021-05-02 23:45:47,523 - Unauthorized: /api/login_history
- WARNING - 2021-05-02 23:57:32,947 - Unauthorized: /api/login_history
- WARNING - 2021-05-02 23:57:32,953 - Unauthorized: /api/user
- WARNING - 2021-05-03 00:02:00,152 - Unauthorized: /api/user
- WARNING - 2021-05-03 00:02:00,154 - Unauthorized: /api/login_history
- WARNING - 2021-05-03 00:04:15,733 - Unauthorized: /api/login_history
- WARNING - 2021-05-03 00:04:15,744 - Unauthorized: /api/user
- WARNING - 2021-05-03 00:09:52,129 - Unauthorized: /api/user
- WARNING - 2021-05-03 00:09:52,144 - Unauthorized: /api/login_history
- WARNING - 2021-05-03 00:09:58,060 - Unauthorized: /api/login_history
- WARNING - 2021-05-03 00:09:58,067 - Unauthorized: /api/user
- WARNING - 2021-05-03 00:15:10,471 - Unauthorized: /api/user
- WARNING - 2021-05-03 00:15:10,476 - Unauthorized: /api/login_history
- WARNING - 2021-05-03 00:15:48,566 - Unauthorized: /api/user
- WARNING - 2021-05-03 00:15:48,607 - Unauthorized: /api/login_history
- WARNING - 2021-05-03 00:17:02,387 - Unauthorized: /api/user
- WARNING - 2021-05-03 00:17:02,391 - Unauthorized: /api/login_history
- WARNING - 2021-05-03 00:17:13,918 - Unauthorized: /api/user
- WARNING - 2021-05-03 00:17:13,920 - Unauthorized: /api/login_history
- WARNING - 2021-05-03 11:15:25,617 - Not Found: /
- WARNING - 2021-05-03 11:15:25,736 - Not Found: /
- WARNING - 2021-05-03 11:15:26,737 - Not Found: /
- WARNING - 2021-05-03 11:15:27,741 - Not Found: /
- WARNING - 2021-05-03 11:15:28,737 - Not Found: /
- WARNING - 2021-05-03 11:15:29,738 - Not Found: /
- WARNING - 2021-05-03 11:15:30,741 - Not Found: /
- WARNING - 2021-05-03 11:15:31,740 - Not Found: /
- WARNING - 2021-05-03 11:15:32,738 - Not Found: /
- WARNING - 2021-05-03 11:15:33,744 - Not Found: /
- WARNING - 2021-05-03 11:15:34,735 - Not Found: /
- WARNING - 2021-05-03 11:15:35,813 - Not Found: /
- WARNING - 2021-05-03 11:15:36,745 - Not Found: /
- WARNING - 2021-05-03 11:15:37,770 - Not Found: /
- WARNING - 2021-05-03 11:15:38,738 - Not Found: /
- WARNING - 2021-05-03 11:15:39,737 - Not Found: /
- WARNING - 2021-05-03 11:15:40,732 - Not Found: /
- WARNING - 2021-05-03 11:15:41,734 - Not Found: /
- WARNING - 2021-05-03 11:15:42,744 - Not Found: /
- WARNING - 2021-05-03 11:15:43,810 - Not Found: /
- WARNING - 2021-05-03 11:15:44,736 - Not Found: /
- WARNING - 2021-05-03 11:15:45,749 - Not Found: /
- WARNING - 2021-05-03 11:15:46,759 - Not Found: /
- WARNING - 2021-05-03 11:15:47,854 - Not Found: /
- WARNING - 2021-05-03 11:15:48,739 - Not Found: /
- WARNING - 2021-05-03 11:15:49,735 - Not Found: /
- WARNING - 2021-05-03 11:15:50,737 - Not Found: /
- WARNING - 2021-05-03 11:15:51,737 - Not Found: /
- WARNING - 2021-05-03 11:15:52,738 - Not Found: /
- WARNING - 2021-05-03 11:15:53,741 - Not Found: /
- WARNING - 2021-05-03 11:15:54,807 - Not Found: /
- WARNING - 2021-05-03 11:15:55,769 - Not Found: /
- WARNING - 2021-05-03 11:15:56,882 - Not Found: /
- WARNING - 2021-05-03 11:15:57,732 - Not Found: /
- WARNING - 2021-05-03 11:15:58,747 - Not Found: /
- WARNING - 2021-05-03 11:15:59,741 - Not Found: /
- WARNING - 2021-05-03 11:16:00,740 - Not Found: /
- WARNING - 2021-05-03 11:16:01,733 - Not Found: /
- WARNING - 2021-05-03 11:16:02,760 - Not Found: /
- WARNING - 2021-05-03 11:16:03,746 - Not Found: /
- WARNING - 2021-05-03 11:16:04,800 - Not Found: /
- WARNING - 2021-05-03 11:16:05,732 - Not Found: /
- WARNING - 2021-05-03 11:16:06,740 - Not Found: /
- WARNING - 2021-05-03 11:16:07,735 - Not Found: /
- WARNING - 2021-05-03 11:16:08,737 - Not Found: /
- WARNING - 2021-05-03 11:16:09,729 - Not Found: /
- WARNING - 2021-05-03 11:16:10,804 - Not Found: /
- WARNING - 2021-05-03 11:16:11,741 - Not Found: /
- WARNING - 2021-05-03 11:16:12,743 - Not Found: /
- WARNING - 2021-05-03 11:16:13,816 - Not Found: /
- WARNING - 2021-05-03 11:16:14,735 - Not Found: /
- WARNING - 2021-05-03 11:16:15,734 - Not Found: /
- WARNING - 2021-05-03 11:16:16,748 - Not Found: /
- WARNING - 2021-05-03 11:16:17,732 - Not Found: /
- WARNING - 2021-05-03 11:16:18,760 - Not Found: /
- WARNING - 2021-05-03 11:16:19,739 - Not Found: /
- WARNING - 2021-05-03 11:16:20,735 - Not Found: /
- WARNING - 2021-05-03 11:16:21,785 - Not Found: /
- WARNING - 2021-05-03 11:16:22,737 - Not Found: /
- WARNING - 2021-05-03 11:16:23,747 - Not Found: /
- WARNING - 2021-05-03 11:16:24,748 - Not Found: /
- WARNING - 2021-05-03 11:16:25,750 - Not Found: /
- WARNING - 2021-05-03 11:16:26,865 - Not Found: /
- WARNING - 2021-05-03 11:16:27,896 - Not Found: /
- WARNING - 2021-05-03 11:16:28,755 - Not Found: /
- WARNING - 2021-05-03 11:16:29,853 - Not Found: /
- WARNING - 2021-05-03 11:16:30,735 - Not Found: /
- WARNING - 2021-05-03 11:16:31,793 - Not Found: /
- WARNING - 2021-05-03 11:16:32,740 - Not Found: /
- WARNING - 2021-05-03 11:16:33,772 - Not Found: /
- WARNING - 2021-05-03 11:16:34,734 - Not Found: /
- WARNING - 2021-05-03 11:16:35,744 - Not Found: /
- WARNING - 2021-05-03 11:16:36,766 - Not Found: /
- WARNING - 2021-05-03 11:16:37,737 - Not Found: /
- WARNING - 2021-05-03 11:16:38,753 - Not Found: /
- WARNING - 2021-05-03 11:16:39,775 - Not Found: /
- WARNING - 2021-05-03 11:16:40,825 - Not Found: /
- WARNING - 2021-05-03 11:16:41,736 - Not Found: /
- WARNING - 2021-05-03 11:16:42,741 - Not Found: /
- WARNING - 2021-05-03 11:16:43,752 - Not Found: /
- WARNING - 2021-05-03 11:16:44,787 - Not Found: /
- WARNING - 2021-05-03 11:16:45,766 - Not Found: /
- WARNING - 2021-05-03 11:16:46,735 - Not Found: /
- WARNING - 2021-05-03 11:16:47,736 - Not Found: /
- WARNING - 2021-05-03 11:16:48,804 - Not Found: /
- WARNING - 2021-05-03 11:16:49,857 - Not Found: /
- WARNING - 2021-05-03 11:16:50,741 - Not Found: /
- WARNING - 2021-05-03 11:24:11,265 - Not Found: /
- WARNING - 2021-05-03 11:24:12,032 - Not Found: /
- WARNING - 2021-05-03 11:24:13,038 - Not Found: /
- WARNING - 2021-05-03 11:24:14,035 - Not Found: /
- WARNING - 2021-05-03 11:24:15,032 - Not Found: /
- WARNING - 2021-05-03 11:24:16,033 - Not Found: /
- WARNING - 2021-05-03 11:24:17,038 - Not Found: /
- WARNING - 2021-05-03 11:24:18,034 - Not Found: /
- WARNING - 2021-05-03 11:24:19,180 - Not Found: /
- WARNING - 2021-05-03 11:24:20,057 - Not Found: /
- WARNING - 2021-05-03 11:24:21,061 - Not Found: /
- WARNING - 2021-05-03 11:24:22,031 - Not Found: /
- WARNING - 2021-05-03 11:24:23,082 - Not Found: /
- WARNING - 2021-05-03 11:24:24,064 - Not Found: /
- WARNING - 2021-05-03 11:24:25,026 - Not Found: /
- WARNING - 2021-05-03 11:24:26,048 - Not Found: /
- WARNING - 2021-05-03 11:24:27,075 - Not Found: /
- WARNING - 2021-05-03 11:24:28,079 - Not Found: /
- WARNING - 2021-05-03 11:24:29,071 - Not Found: /
- WARNING - 2021-05-03 11:24:30,045 - Not Found: /
- WARNING - 2021-05-03 11:24:31,035 - Not Found: /
- WARNING - 2021-05-03 11:24:32,036 - Not Found: /
- WARNING - 2021-05-03 11:24:33,105 - Not Found: /
- WARNING - 2021-05-03 11:24:34,028 - Not Found: /
- WARNING - 2021-05-03 11:24:35,033 - Not Found: /
- WARNING - 2021-05-03 11:24:36,031 - Not Found: /
- WARNING - 2021-05-03 11:24:37,043 - Not Found: /
- WARNING - 2021-05-03 11:24:38,108 - Not Found: /
- WARNING - 2021-05-03 11:24:39,034 - Not Found: /
- WARNING - 2021-05-03 11:24:40,045 - Not Found: /
- WARNING - 2021-05-03 11:24:41,044 - Not Found: /
- WARNING - 2021-05-03 11:24:42,158 - Not Found: /
- WARNING - 2021-05-03 11:24:43,030 - Not Found: /
- WARNING - 2021-05-03 11:24:44,023 - Not Found: /
- WARNING - 2021-05-03 11:24:45,040 - Not Found: /
- WARNING - 2021-05-03 11:24:46,043 - Not Found: /
- WARNING - 2021-05-03 11:24:47,028 - Not Found: /
- WARNING - 2021-05-03 11:24:48,171 - Not Found: /
- WARNING - 2021-05-03 11:24:49,034 - Not Found: /
- WARNING - 2021-05-03 11:24:50,027 - Not Found: /
- WARNING - 2021-05-03 11:24:51,033 - Not Found: /
- WARNING - 2021-05-03 11:24:52,030 - Not Found: /
- WARNING - 2021-05-03 11:24:53,023 - Not Found: /
- WARNING - 2021-05-03 11:24:54,129 - Not Found: /
- WARNING - 2021-05-03 11:24:55,043 - Not Found: /
- WARNING - 2021-05-03 11:24:56,029 - Not Found: /
- WARNING - 2021-05-03 11:24:57,026 - Not Found: /
- WARNING - 2021-05-03 11:24:58,032 - Not Found: /
- WARNING - 2021-05-03 11:24:59,079 - Not Found: /
- WARNING - 2021-05-03 11:25:00,030 - Not Found: /
- WARNING - 2021-05-03 11:25:01,024 - Not Found: /
- WARNING - 2021-05-03 11:25:02,028 - Not Found: /
- WARNING - 2021-05-03 11:25:03,059 - Not Found: /
- WARNING - 2021-05-03 11:25:04,032 - Not Found: /
- WARNING - 2021-05-03 11:25:05,046 - Not Found: /
- WARNING - 2021-05-03 11:25:06,080 - Not Found: /
- WARNING - 2021-05-03 11:25:07,103 - Not Found: /
- WARNING - 2021-05-03 11:25:08,044 - Not Found: /
- WARNING - 2021-05-03 11:25:09,030 - Not Found: /
- WARNING - 2021-05-03 11:25:10,048 - Not Found: /
- WARNING - 2021-05-03 11:25:11,028 - Not Found: /
- WARNING - 2021-05-03 11:25:12,056 - Not Found: /
- WARNING - 2021-05-03 11:25:13,114 - Not Found: /
- WARNING - 2021-05-03 11:25:14,031 - Not Found: /
- WARNING - 2021-05-03 11:25:15,033 - Not Found: /
- WARNING - 2021-05-03 11:25:16,088 - Not Found: /
- WARNING - 2021-05-03 11:25:17,041 - Not Found: /
- WARNING - 2021-05-03 11:25:18,026 - Not Found: /
- WARNING - 2021-05-03 11:25:19,082 - Not Found: /
- WARNING - 2021-05-03 11:25:20,028 - Not Found: /
- WARNING - 2021-05-03 11:25:21,094 - Not Found: /
- WARNING - 2021-05-03 11:25:22,023 - Not Found: /
- WARNING - 2021-05-03 11:25:23,032 - Not Found: /
- WARNING - 2021-05-03 11:25:24,027 - Not Found: /
- WARNING - 2021-05-03 11:25:25,025 - Not Found: /
- WARNING - 2021-05-03 11:25:26,030 - Not Found: /
- WARNING - 2021-05-03 11:25:27,071 - Not Found: /
- WARNING - 2021-05-03 11:25:28,038 - Not Found: /
- WARNING - 2021-05-03 11:25:29,033 - Not Found: /
- WARNING - 2021-05-03 11:25:30,027 - Not Found: /
- WARNING - 2021-05-03 11:25:31,032 - Not Found: /
- WARNING - 2021-05-03 11:25:32,052 - Not Found: /
- WARNING - 2021-05-03 11:25:33,037 - Not Found: /
- WARNING - 2021-05-03 11:25:34,034 - Not Found: /
- WARNING - 2021-05-03 11:25:35,094 - Not Found: /
- WARNING - 2021-05-03 11:25:36,032 - Not Found: /
- WARNING - 2021-05-03 11:25:37,041 - Not Found: /
- WARNING - 2021-05-03 11:25:38,033 - Not Found: /
- WARNING - 2021-05-03 11:25:39,031 - Not Found: /
- WARNING - 2021-05-03 11:25:40,044 - Not Found: /
- WARNING - 2021-05-03 11:25:41,034 - Not Found: /
- WARNING - 2021-05-03 11:25:42,031 - Not Found: /
- WARNING - 2021-05-03 11:25:43,115 - Not Found: /
- WARNING - 2021-05-03 11:25:44,032 - Not Found: /
- WARNING - 2021-05-03 11:25:45,032 - Not Found: /
- WARNING - 2021-05-03 11:25:46,062 - Not Found: /
- WARNING - 2021-05-03 11:25:47,025 - Not Found: /
- WARNING - 2021-05-03 11:25:48,033 - Not Found: /
- WARNING - 2021-05-03 11:25:49,034 - Not Found: /
- WARNING - 2021-05-03 11:25:50,154 - Not Found: /
- WARNING - 2021-05-03 11:25:51,042 - Not Found: /
- WARNING - 2021-05-03 11:25:52,033 - Not Found: /
- INFO - 2021-05-03 11:25:52,114 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- WARNING - 2021-05-03 11:26:07,288 - Not Found: /
- WARNING - 2021-05-03 11:26:08,026 - Not Found: /
- WARNING - 2021-05-03 11:26:09,028 - Not Found: /
- WARNING - 2021-05-03 11:26:10,039 - Not Found: /
- WARNING - 2021-05-03 11:26:11,024 - Not Found: /
- WARNING - 2021-05-03 11:26:12,030 - Not Found: /
- WARNING - 2021-05-03 11:26:13,041 - Not Found: /
- WARNING - 2021-05-03 11:26:14,234 - Not Found: /
- WARNING - 2021-05-03 11:26:15,069 - Not Found: /
- WARNING - 2021-05-03 11:26:16,032 - Not Found: /
- WARNING - 2021-05-03 11:26:17,032 - Not Found: /
- WARNING - 2021-05-03 11:26:18,031 - Not Found: /
- WARNING - 2021-05-03 11:26:19,038 - Not Found: /
- WARNING - 2021-05-03 11:26:20,038 - Not Found: /
- WARNING - 2021-05-03 11:26:21,026 - Not Found: /
- INFO - 2021-05-03 11:26:21,431 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- WARNING - 2021-05-03 11:26:36,183 - Not Found: /
- WARNING - 2021-05-03 11:26:37,029 - Not Found: /
- WARNING - 2021-05-03 11:26:38,031 - Not Found: /
- WARNING - 2021-05-03 11:26:39,081 - Not Found: /
- WARNING - 2021-05-03 11:26:40,032 - Not Found: /
- WARNING - 2021-05-03 11:26:41,048 - Not Found: /
- WARNING - 2021-05-03 11:26:42,041 - Not Found: /
- WARNING - 2021-05-03 11:26:43,098 - Not Found: /
- WARNING - 2021-05-03 11:26:44,028 - Not Found: /
- WARNING - 2021-05-03 11:26:45,030 - Not Found: /
- WARNING - 2021-05-03 11:26:46,031 - Not Found: /
- WARNING - 2021-05-03 11:26:47,030 - Not Found: /
- WARNING - 2021-05-03 11:26:48,032 - Not Found: /
- WARNING - 2021-05-03 11:26:49,041 - Not Found: /
- WARNING - 2021-05-03 11:26:50,093 - Not Found: /
- WARNING - 2021-05-03 11:26:51,037 - Not Found: /
- WARNING - 2021-05-03 11:26:52,054 - Not Found: /
- WARNING - 2021-05-03 11:26:53,041 - Not Found: /
- INFO - 2021-05-03 11:26:53,287 - D:\GitHub\secure-file-storage-app\api\file_manager\user\urls.py changed, reloading.
- WARNING - 2021-05-03 11:27:09,207 - Not Found: /
- WARNING - 2021-05-03 11:27:10,029 - Not Found: /
- WARNING - 2021-05-03 11:27:11,027 - Not Found: /
- WARNING - 2021-05-03 11:27:12,028 - Not Found: /
- WARNING - 2021-05-03 11:27:13,027 - Not Found: /
- WARNING - 2021-05-03 11:27:14,075 - Not Found: /
- INFO - 2021-05-03 22:06:17,355 - Init Server
- INFO - 2021-05-03 22:06:38,577 - Init Server
- INFO - 2021-05-03 22:07:10,716 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-03 22:07:12,672 - get_file_list
- INFO - 2021-05-03 22:09:52,434 - get_file_list
- INFO - 2021-05-03 22:21:19,249 - Init Server
- INFO - 2021-05-03 22:21:28,227 - Init Server
- INFO - 2021-05-03 22:21:47,001 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-03 22:33:30,139 - Init Server
- INFO - 2021-05-03 22:33:30,208 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-03 22:34:18,433 - D:\GitHub\secure-file-storage-app\api\file_manager\file_storage\file_storage.py changed, reloading.
- INFO - 2021-05-03 22:35:35,376 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-03 22:36:01,306 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- WARNING - 2021-05-03 22:49:44,910 - Unauthorized: /api/login_history
- WARNING - 2021-05-03 22:49:44,919 - Unauthorized: /api/user
- WARNING - 2021-05-03 22:50:24,340 - Bad Request: /api/login
- INFO - 2021-05-03 22:58:50,087 - Init Server
- INFO - 2021-05-03 22:58:50,136 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-03 22:58:54,200 - upload_file -> (file_name: github.com_Merevoli-DatLuu_MST_blob_main_main.cpp (1).png.aes)
- WARNING - 2021-05-03 23:07:22,483 - Unauthorized: /api/user
- WARNING - 2021-05-03 23:07:22,520 - Unauthorized: /api/login_history
- INFO - 2021-05-03 23:08:28,668 - D:\GitHub\secure-file-storage-app\api\file_manager\file_storage\file_storage.py changed, reloading.
- INFO - 2021-05-03 23:09:40,957 - D:\GitHub\secure-file-storage-app\api\file_manager\file_storage\file_storage.py changed, reloading.
- INFO - 2021-05-03 23:10:20,341 - Init Server
- INFO - 2021-05-03 23:10:30,399 - Init Server
- INFO - 2021-05-03 23:10:49,365 - access_token is expired. Now: 2021-05-03 16:10:49.365113, token_expiry: 2021-05-03 16:03:34
- INFO - 2021-05-03 23:10:49,367 - access_token is expired. Now: 2021-05-03 16:10:49.366113, token_expiry: 2021-05-03 16:03:34
- INFO - 2021-05-03 23:10:52,984 - Received token response with no refresh_token. Consider reauthenticating with prompt='consent'.
- INFO - 2021-05-03 23:10:52,985 - Successfully retrieved access token
- INFO - 2021-05-03 23:10:53,056 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-03 23:10:54,559 - get_file_list
- INFO - 2021-05-03 23:11:01,634 - get_file_list
- WARNING - 2021-05-04 14:25:12,004 - Bad Request: /api/login
- WARNING - 2021-05-04 14:26:10,323 - Bad Request: /api/login
- WARNING - 2021-05-04 14:26:29,762 - Bad Request: /api/login
- WARNING - 2021-05-04 14:26:59,177 - Bad Request: /api/login
- WARNING - 2021-05-04 14:27:14,775 - Bad Request: /api/login
- WARNING - 2021-05-04 14:58:43,377 - Not Found: /api/register
- WARNING - 2021-05-04 14:59:29,623 - Bad Request: /api/reister
- WARNING - 2021-05-04 15:00:46,256 - Bad Request: /api/register
- WARNING - 2021-05-04 15:01:06,313 - Bad Request: /api/register
- WARNING - 2021-05-04 15:01:18,393 - Bad Request: /api/register
- WARNING - 2021-05-04 15:01:33,379 - Bad Request: /api/register
- INFO - 2021-05-04 15:01:56,320 - Init Server
- INFO - 2021-05-04 15:01:56,320 - access_token is expired. Now: 2021-05-04 08:01:56.320419, token_expiry: 2021-05-03 16:03:34
- INFO - 2021-05-04 15:01:56,324 - access_token is expired. Now: 2021-05-04 08:01:56.324419, token_expiry: 2021-05-03 16:03:34
- WARNING - 2021-05-04 15:02:49,739 - Bad Request: /api/register
- INFO - 2021-05-04 15:03:18,002 - Init Server
- INFO - 2021-05-04 15:03:18,003 - access_token is expired. Now: 2021-05-04 08:03:18.003995, token_expiry: 2021-05-03 16:03:34
- INFO - 2021-05-04 15:03:18,009 - access_token is expired. Now: 2021-05-04 08:03:18.009995, token_expiry: 2021-05-03 16:03:34
- INFO - 2021-05-04 15:03:41,001 - Init Server
- INFO - 2021-05-04 15:03:41,001 - access_token is expired. Now: 2021-05-04 08:03:41.001590, token_expiry: 2021-05-03 16:03:34
- INFO - 2021-05-04 15:03:41,007 - access_token is expired. Now: 2021-05-04 08:03:41.007590, token_expiry: 2021-05-03 16:03:34
- INFO - 2021-05-04 15:03:42,445 - Received token response with no refresh_token. Consider reauthenticating with prompt='consent'.
- INFO - 2021-05-04 15:03:42,446 - Successfully retrieved access token
- INFO - 2021-05-04 15:03:42,793 - file_cache is only supported with oauth2client<4.0.0
- ERROR - 2021-05-04 15:03:42,801 - Internal Server Error: /api/register
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py", line 32, in post
    file_storage.create_folder(serializer.validated_data['email'])
  File "./file_storage\file_storage.py", line 88, in create_folder
    folder.Upload()
  File "C:\Python37\lib\site-packages\pydrive\files.py", line 285, in Upload
    self._FilesInsert(param=param)
  File "C:\Python37\lib\site-packages\pydrive\auth.py", line 57, in _decorated
    self.auth.LocalWebserverAuth()
  File "C:\Python37\lib\site-packages\pydrive\auth.py", line 122, in _decorated
    code = decoratee(self, *args, **kwargs)
  File "C:\Python37\lib\site-packages\pydrive\auth.py", line 241, in LocalWebserverAuth
    raise AuthenticationError('No code found in redirect')
pydrive.auth.AuthenticationError: No code found in redirect
- WARNING - 2021-05-04 15:05:15,191 - Not Found: /favicon.ico
- INFO - 2021-05-04 15:05:30,020 - Init Server
- INFO - 2021-05-04 15:05:30,020 - access_token is expired. Now: 2021-05-04 08:05:30.020874, token_expiry: 2021-05-03 16:03:34
- INFO - 2021-05-04 15:05:30,027 - access_token is expired. Now: 2021-05-04 08:05:30.027874, token_expiry: 2021-05-03 16:03:34
- WARNING - 2021-05-04 15:06:19,861 - Bad Request: /api/register
- INFO - 2021-05-04 15:06:57,211 - Init Server
- INFO - 2021-05-04 15:06:57,211 - access_token is expired. Now: 2021-05-04 08:06:57.211948, token_expiry: 2021-05-03 16:03:34
- INFO - 2021-05-04 15:06:57,216 - access_token is expired. Now: 2021-05-04 08:06:57.216948, token_expiry: 2021-05-03 16:03:34
- INFO - 2021-05-04 15:06:59,576 - Received token response with no refresh_token. Consider reauthenticating with prompt='consent'.
- INFO - 2021-05-04 15:06:59,576 - Successfully retrieved access token
- INFO - 2021-05-04 15:06:59,616 - file_cache is only supported with oauth2client<4.0.0
- WARNING - 2021-05-05 11:43:00,449 - Not Found: /
- WARNING - 2021-05-05 11:43:02,664 - Not Found: /favicon.ico
- WARNING - 2021-05-07 09:31:47,428 - Bad Request: /api/login
- WARNING - 2021-05-07 09:31:47,619 - Bad Request: /api/login
- WARNING - 2021-05-07 09:32:03,254 - Bad Request: /api/login
- WARNING - 2021-05-07 09:44:07,553 - Bad Request: /api/login
- WARNING - 2021-05-07 09:48:46,969 - Bad Request: /api/login
- WARNING - 2021-05-07 09:49:04,084 - Bad Request: /api/login
- WARNING - 2021-05-07 09:51:24,954 - Bad Request: /api/login
- WARNING - 2021-05-07 09:52:55,085 - Bad Request: /api/login
- WARNING - 2021-05-07 09:52:59,056 - Bad Request: /api/login
- WARNING - 2021-05-07 09:53:02,416 - Bad Request: /api/login
- WARNING - 2021-05-07 09:56:48,856 - Bad Request: /api/login
- WARNING - 2021-05-07 09:57:01,399 - Bad Request: /api/login
- WARNING - 2021-05-07 09:57:18,964 - Bad Request: /api/login
- WARNING - 2021-05-07 09:57:21,158 - Bad Request: /api/login
- WARNING - 2021-05-07 09:58:11,969 - Bad Request: /api/login
- WARNING - 2021-05-07 09:58:21,112 - Bad Request: /api/login
- WARNING - 2021-05-07 09:58:24,410 - Bad Request: /api/login
- WARNING - 2021-05-07 09:58:28,565 - Bad Request: /api/login
- WARNING - 2021-05-07 10:03:46,154 - Bad Request: /api/login
- WARNING - 2021-05-07 10:04:47,585 - Bad Request: /api/register
- WARNING - 2021-05-07 10:04:50,776 - Bad Request: /api/register
- WARNING - 2021-05-07 10:05:05,661 - Bad Request: /api/register
- WARNING - 2021-05-07 10:05:09,822 - Bad Request: /api/register
- WARNING - 2021-05-07 10:06:23,994 - Bad Request: /api/register
- WARNING - 2021-05-07 10:06:28,381 - Bad Request: /api/register
- WARNING - 2021-05-07 10:07:39,132 - Bad Request: /api/login
- WARNING - 2021-05-07 10:07:55,732 - Bad Request: /api/register
- WARNING - 2021-05-07 10:08:00,761 - Bad Request: /api/register
- WARNING - 2021-05-07 10:12:16,407 - Unauthorized: /api/user
- WARNING - 2021-05-07 10:12:16,413 - Unauthorized: /api/login_history
- WARNING - 2021-05-07 10:14:24,003 - Unauthorized: /api/login_history
- WARNING - 2021-05-07 10:14:24,008 - Unauthorized: /api/user
- WARNING - 2021-05-07 10:14:27,739 - Bad Request: /api/register
- WARNING - 2021-05-07 10:18:03,347 - Unauthorized: /api/user
- WARNING - 2021-05-07 10:18:03,350 - Unauthorized: /api/login_history
- WARNING - 2021-05-07 10:18:45,091 - Bad Request: /api/login
- WARNING - 2021-05-07 10:20:34,280 - Unauthorized: /api/user
- WARNING - 2021-05-07 10:20:34,285 - Unauthorized: /api/login_history
- WARNING - 2021-05-07 10:20:54,502 - Bad Request: /api/login
- WARNING - 2021-05-07 10:21:24,796 - Unauthorized: /api/user
- WARNING - 2021-05-07 10:21:24,798 - Unauthorized: /api/login_history
- WARNING - 2021-05-07 10:21:45,910 - Bad Request: /api/login
- WARNING - 2021-05-07 10:26:46,624 - Unauthorized: /api/user
- WARNING - 2021-05-07 10:26:46,630 - Unauthorized: /api/login_history
- WARNING - 2021-05-07 10:28:40,509 - Unauthorized: /api/user
- WARNING - 2021-05-07 10:28:40,516 - Unauthorized: /api/login_history
- WARNING - 2021-05-07 10:34:02,516 - Unauthorized: /api/user
- WARNING - 2021-05-07 10:34:02,520 - Unauthorized: /api/login_history
- WARNING - 2021-05-07 10:34:32,191 - Unauthorized: /api/file
- WARNING - 2021-05-07 10:34:32,207 - Unauthorized: /api/file
- WARNING - 2021-05-07 10:34:32,233 - Unauthorized: /api/file
- WARNING - 2021-05-07 10:34:32,243 - Unauthorized: /api/file
- WARNING - 2021-05-07 10:34:32,243 - Unauthorized: /api/file
- WARNING - 2021-05-07 10:34:32,248 - Unauthorized: /api/file
- WARNING - 2021-05-07 10:42:00,603 - Unauthorized: /api/user
- WARNING - 2021-05-07 10:42:00,615 - Unauthorized: /api/login_history
- WARNING - 2021-05-07 10:42:52,357 - Unauthorized: /api/user
- WARNING - 2021-05-07 10:42:52,360 - Unauthorized: /api/login_history
- WARNING - 2021-05-07 10:44:08,701 - Unauthorized: /api/user
- WARNING - 2021-05-07 10:44:08,742 - Unauthorized: /api/login_history
- WARNING - 2021-05-07 10:44:45,488 - Unauthorized: /api/user
- WARNING - 2021-05-07 10:44:45,499 - Unauthorized: /api/login_history
- WARNING - 2021-05-07 10:48:37,751 - Unauthorized: /api/user
- WARNING - 2021-05-07 10:48:37,762 - Unauthorized: /api/login_history
- WARNING - 2021-05-07 10:59:17,674 - Unauthorized: /api/user
- WARNING - 2021-05-07 10:59:17,681 - Unauthorized: /api/login_history
- WARNING - 2021-05-07 11:10:04,518 - Unauthorized: /api/user
- WARNING - 2021-05-07 11:10:04,533 - Unauthorized: /api/login_history
- WARNING - 2021-05-07 11:11:47,355 - Unauthorized: /api/user
- WARNING - 2021-05-07 11:11:47,359 - Unauthorized: /api/login_history
- WARNING - 2021-05-07 11:13:34,634 - Unauthorized: /api/user
- WARNING - 2021-05-07 11:13:34,639 - Unauthorized: /api/login_history
- WARNING - 2021-05-07 11:14:36,288 - Unauthorized: /api/user
- WARNING - 2021-05-07 11:14:36,294 - Unauthorized: /api/login_history
- WARNING - 2021-05-07 11:15:37,306 - Unauthorized: /api/user
- WARNING - 2021-05-07 11:15:37,309 - Unauthorized: /api/login_history
- WARNING - 2021-05-07 11:16:18,584 - Unauthorized: /api/user
- WARNING - 2021-05-07 11:16:18,588 - Unauthorized: /api/login_history
- WARNING - 2021-05-07 11:19:07,125 - Unauthorized: /api/user
- WARNING - 2021-05-07 11:19:07,128 - Unauthorized: /api/login_history
- WARNING - 2021-05-07 11:20:04,178 - Unauthorized: /api/login_history
- WARNING - 2021-05-07 11:20:04,183 - Unauthorized: /api/user
- WARNING - 2021-05-07 12:00:46,891 - Unauthorized: /api/user
- WARNING - 2021-05-07 12:00:46,898 - Unauthorized: /api/login_history
- WARNING - 2021-05-07 12:02:20,256 - Unauthorized: /api/user
- WARNING - 2021-05-07 12:02:20,259 - Unauthorized: /api/login_history
- WARNING - 2021-05-07 12:08:35,117 - Unauthorized: /api/user
- WARNING - 2021-05-07 12:08:35,141 - Unauthorized: /api/login_history
- WARNING - 2021-05-07 12:17:45,268 - Unauthorized: /api/user
- WARNING - 2021-05-07 12:17:45,273 - Unauthorized: /api/login_history
- WARNING - 2021-05-07 12:23:10,182 - Unauthorized: /api/login_history
- WARNING - 2021-05-07 12:23:10,186 - Unauthorized: /api/user
- WARNING - 2021-05-07 13:46:03,469 - Unauthorized: /api/login_history
- WARNING - 2021-05-07 13:46:03,483 - Unauthorized: /api/user
- WARNING - 2021-05-07 13:49:52,043 - Unauthorized: /api/login_history
- WARNING - 2021-05-07 13:49:52,043 - Unauthorized: /api/user
- WARNING - 2021-05-07 17:30:12,903 - Unauthorized: /api/user
- WARNING - 2021-05-07 17:30:12,901 - Unauthorized: /api/login_history
- WARNING - 2021-05-07 17:44:59,039 - Unauthorized: /api/user
- WARNING - 2021-05-07 17:44:59,043 - Unauthorized: /api/login_history
- WARNING - 2021-05-07 18:15:22,341 - Unauthorized: /api/user
- WARNING - 2021-05-07 18:15:22,346 - Unauthorized: /api/login_history
- WARNING - 2021-05-07 19:17:21,405 - Unauthorized: /api/user
- WARNING - 2021-05-07 19:17:21,410 - Unauthorized: /api/login_history
- WARNING - 2021-05-07 19:17:24,830 - Unauthorized: /api/login_history
- WARNING - 2021-05-07 19:17:27,437 - Unauthorized: /api/login_history
- WARNING - 2021-05-07 19:17:51,191 - Unauthorized: /api/login_history
- WARNING - 2021-05-07 19:18:17,151 - Unauthorized: /api/login_history
- WARNING - 2021-05-07 19:18:22,448 - Unauthorized: /api/login_history
- WARNING - 2021-05-07 19:18:37,674 - Unauthorized: /api/login_history
- WARNING - 2021-05-07 19:18:37,685 - Unauthorized: /api/user
- INFO - 2021-05-07 20:14:01,740 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- INFO - 2021-05-07 20:15:03,458 - D:\GitHub\secure-file-storage-app\api\file_manager\user\serializers.py changed, reloading.
- INFO - 2021-05-07 20:15:31,351 - D:\GitHub\secure-file-storage-app\api\file_manager\user\serializers.py changed, reloading.
- INFO - 2021-05-07 20:15:56,886 - D:\GitHub\secure-file-storage-app\api\file_manager\user\serializers.py changed, reloading.
- INFO - 2021-05-07 20:16:28,731 - D:\GitHub\secure-file-storage-app\api\file_manager\user\serializers.py changed, reloading.
- INFO - 2021-05-07 20:16:53,836 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- INFO - 2021-05-07 20:17:19,519 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- INFO - 2021-05-07 20:17:48,051 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- INFO - 2021-05-07 20:49:10,705 - D:\GitHub\secure-file-storage-app\api\file_manager\user\urls.py changed, reloading.
- INFO - 2021-05-07 20:50:32,377 - D:\GitHub\secure-file-storage-app\api\file_manager\user\urls.py changed, reloading.
- WARNING - 2021-05-07 20:51:00,679 - Bad Request: /api/login
- WARNING - 2021-05-07 20:52:05,502 - Method Not Allowed: /api/change_password
- ERROR - 2021-05-07 20:52:12,283 - Internal Server Error: /api/change_password
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py", line 94, in post
    if serializer.is_valid():
  File "C:\Python37\lib\site-packages\rest_framework\serializers.py", line 220, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "C:\Python37\lib\site-packages\rest_framework\serializers.py", line 419, in run_validation
    value = self.to_internal_value(data)
  File "C:\Python37\lib\site-packages\rest_framework\serializers.py", line 472, in to_internal_value
    for field in fields:
  File "C:\Python37\lib\site-packages\rest_framework\serializers.py", line 355, in _writable_fields
    for field in self.fields.values():
  File "C:\Python37\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Python37\lib\site-packages\rest_framework\serializers.py", line 349, in fields
    for key, value in self.get_fields().items():
  File "C:\Python37\lib\site-packages\rest_framework\serializers.py", line 1006, in get_fields
    serializer_class=self.__class__.__name__
AssertionError: Class UserChangePasswordSerializer missing "Meta" attribute
- INFO - 2021-05-07 20:52:29,852 - D:\GitHub\secure-file-storage-app\api\file_manager\user\serializers.py changed, reloading.
- ERROR - 2021-05-07 20:52:49,694 - Internal Server Error: /api/change_password
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py", line 96, in post
    request.user.set_password(serializer.validated_data['device_info']['password'])
KeyError: 'device_info'
- INFO - 2021-05-07 20:53:12,071 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- INFO - 2021-05-07 20:53:45,426 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- WARNING - 2021-05-07 20:54:19,413 - Bad Request: /api/login
- INFO - 2021-05-07 21:59:50,114 - Init Server
- INFO - 2021-05-07 21:59:50,177 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-07 21:59:52,655 - upload_file -> (file_name: Algorithm PD.docx.aes)
- INFO - 2021-05-07 22:01:34,019 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-07 22:02:48,144 - Init Server
- INFO - 2021-05-07 22:02:48,240 - file_cache is only supported with oauth2client<4.0.0
- ERROR - 2021-05-07 22:02:49,636 - Internal Server Error: /api/file
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 426, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
- INFO - 2021-05-07 22:03:47,526 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- INFO - 2021-05-07 22:05:50,124 - Init Server
- INFO - 2021-05-07 22:05:50,221 - file_cache is only supported with oauth2client<4.0.0
- ERROR - 2021-05-07 22:05:52,134 - Internal Server Error: /api/file
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 426, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
- INFO - 2021-05-07 22:10:26,135 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- INFO - 2021-05-07 22:11:53,811 - Init Server
- INFO - 2021-05-07 22:11:53,910 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-07 22:12:05,217 - upload_file -> (file_name: Modern Vim Craft Your Development Environment with Vim 8 and Neovim by Drew Neil (z-lib.org).pdf.aes)
- INFO - 2021-05-07 22:16:40,467 - Init Server
- INFO - 2021-05-07 22:16:40,567 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-07 22:16:44,312 - Init Server
- INFO - 2021-05-07 22:16:44,316 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-07 22:16:46,688 - upload_file -> (file_name: 00003420191006194349.mp4.aes)
- INFO - 2021-05-07 22:16:52,072 - upload_file -> (file_name: 00003320191006194424.mp4.aes)
- INFO - 2021-05-07 22:18:51,955 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-07 22:19:20,428 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-07 22:20:01,023 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-07 22:21:49,167 - Init Server
- INFO - 2021-05-07 22:21:55,973 - Init Server
- INFO - 2021-05-07 22:22:08,555 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-07 22:22:09,446 - get_file_list
- INFO - 2021-05-07 22:31:02,825 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- WARNING - 2021-05-07 22:32:35,709 - Method Not Allowed: /api/file/000033
- WARNING - 2021-05-07 22:32:42,614 - Method Not Allowed: /api/file/000033
- WARNING - 2021-05-07 22:32:49,046 - Method Not Allowed: /api/file/33
- WARNING - 2021-05-07 22:34:01,692 - Method Not Allowed: /api/file/33
- WARNING - 2021-05-07 22:34:09,849 - Method Not Allowed: /api/file
- WARNING - 2021-05-07 22:34:13,289 - Method Not Allowed: /api/file/1
- INFO - 2021-05-07 22:35:24,049 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- WARNING - 2021-05-07 22:35:43,024 - Method Not Allowed: /api/file/1
- INFO - 2021-05-07 22:35:47,765 - Init Server
- INFO - 2021-05-07 22:35:47,858 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-07 22:35:48,802 - get_files_by_title -> (title: map.json)
- INFO - 2021-05-07 22:35:48,802 - get_content_file -> (file : 1r-4t6DsmI89FDjHQdK4oEIYtRFkJxXv7 - map.json)
- ERROR - 2021-05-07 22:35:50,746 - Service Unavailable: /api/file/1
- INFO - 2021-05-07 22:36:29,852 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- WARNING - 2021-05-07 22:36:49,747 - Method Not Allowed: /api/file/1
- WARNING - 2021-05-07 22:36:57,952 - Method Not Allowed: /api/file/1
- INFO - 2021-05-07 22:37:54,896 - D:\GitHub\secure-file-storage-app\api\file_manager\file\urls.py changed, reloading.
- INFO - 2021-05-07 22:38:30,216 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- WARNING - 2021-05-07 22:38:51,634 - Method Not Allowed: /api/file
- WARNING - 2021-05-07 22:42:05,126 - Method Not Allowed: /api/test
- WARNING - 2021-05-07 22:42:07,806 - Method Not Allowed: /api/test
- WARNING - 2021-05-07 22:42:20,345 - Bad Request: /api/test
- INFO - 2021-05-07 22:42:34,158 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- WARNING - 2021-05-07 22:42:53,023 - Method Not Allowed: /api/test
- WARNING - 2021-05-07 22:42:57,924 - Bad Request: /api/test
- INFO - 2021-05-07 22:43:25,180 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- WARNING - 2021-05-07 22:43:53,644 - Not Found: /api/tremove_file
- INFO - 2021-05-07 22:44:05,908 - Init Server
- INFO - 2021-05-07 22:44:05,966 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-07 22:44:07,491 - get_file_list
- INFO - 2021-05-07 22:44:07,492 - get_file_by_id -> (file_id: 1DvkKQnyqgvV8IMzMRonBg5KlOF5M_oIv)
- INFO - 2021-05-07 22:44:08,541 - delete_file_by_id -> (file_id: 1DvkKQnyqgvV8IMzMRonBg5KlOF5M_oIv)
- INFO - 2021-05-07 22:44:47,065 - D:\GitHub\secure-file-storage-app\api\file_manager\file\urls.py changed, reloading.
- WARNING - 2021-05-07 22:45:09,740 - Not Found: /api/remove_file
- WARNING - 2021-05-07 22:45:15,074 - Method Not Allowed: /api/file
- WARNING - 2021-05-07 22:45:22,194 - Method Not Allowed: /api/file
- INFO - 2021-05-07 22:45:28,984 - D:\GitHub\secure-file-storage-app\api\file_manager\file\urls.py changed, reloading.
- INFO - 2021-05-07 22:50:55,920 - D:\GitHub\secure-file-storage-app\api\file_manager\file\urls.py changed, reloading.
- INFO - 2021-05-07 22:55:25,269 - Init Server
- INFO - 2021-05-07 22:55:25,336 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-07 22:55:26,919 - get_file_list
- ERROR - 2021-05-07 22:55:26,921 - Service Unavailable: /api/remove_file
- INFO - 2021-05-07 22:55:45,099 - Init Server
- INFO - 2021-05-07 22:55:45,133 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-07 22:55:46,290 - get_file_list
- INFO - 2021-05-07 22:55:46,290 - get_file_by_id -> (file_id: 15tOqvOBxdCY6ZUMeZGhbcl7GXdT5RoOd)
- INFO - 2021-05-07 22:55:47,316 - delete_file_by_id -> (file_id: 15tOqvOBxdCY6ZUMeZGhbcl7GXdT5RoOd)
- INFO - 2021-05-07 22:56:04,035 - Init Server
- INFO - 2021-05-07 22:56:04,065 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-07 22:56:05,420 - get_file_list
- INFO - 2021-05-07 22:56:05,421 - get_file_by_id -> (file_id: 1MwdxR0RxaRLMELBk0jFUj9fz2UMeawVT)
- INFO - 2021-05-07 22:56:06,650 - delete_file_by_id -> (file_id: 1MwdxR0RxaRLMELBk0jFUj9fz2UMeawVT)
- WARNING - 2021-05-08 11:07:26,233 - Bad Request: /api/login
- WARNING - 2021-05-08 11:09:22,473 - Method Not Allowed: /api/change_password
- WARNING - 2021-05-08 11:09:26,413 - Bad Request: /api/change_password
- ERROR - 2021-05-08 11:09:57,610 - Internal Server Error: /api/change_password
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py", line 97, in post
    if make_password(serializer.validated_data['old_password']) == request.user['password']:
TypeError: 'User' object is not subscriptable
- INFO - 2021-05-08 11:12:14,966 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- WARNING - 2021-05-08 11:12:37,079 - Bad Request: /api/change_password
- INFO - 2021-05-08 11:12:57,889 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- WARNING - 2021-05-08 11:13:14,144 - Bad Request: /api/change_password
- WARNING - 2021-05-08 11:13:18,093 - Bad Request: /api/change_password
- INFO - 2021-05-08 11:13:36,794 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- WARNING - 2021-05-08 11:14:33,044 - Bad Request: /api/change_password
- INFO - 2021-05-08 11:14:43,362 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- WARNING - 2021-05-08 11:15:35,373 - Bad Request: /api/change_password
- WARNING - 2021-05-08 11:15:41,170 - Bad Request: /api/change_password
- WARNING - 2021-05-08 11:15:44,268 - Bad Request: /api/change_password
- WARNING - 2021-05-08 11:15:47,555 - Bad Request: /api/change_password
- WARNING - 2021-05-08 11:16:06,223 - Bad Request: /api/change_password
- INFO - 2021-05-08 11:16:14,850 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- INFO - 2021-05-08 11:16:47,712 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- WARNING - 2021-05-08 11:17:07,863 - Bad Request: /api/change_password
- INFO - 2021-05-08 11:18:36,916 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- WARNING - 2021-05-08 11:19:17,841 - Bad Request: /api/change_password
- WARNING - 2021-05-08 11:19:27,783 - Bad Request: /api/login
- WARNING - 2021-05-08 11:20:11,003 - Bad Request: /api/change_password
- WARNING - 2021-05-08 11:20:15,858 - Bad Request: /api/change_password
- WARNING - 2021-05-08 11:20:20,197 - Bad Request: /api/change_password
- INFO - 2021-05-08 11:20:43,435 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- WARNING - 2021-05-08 11:20:57,513 - Bad Request: /api/change_password
- WARNING - 2021-05-08 11:21:05,947 - Bad Request: /api/change_password
- WARNING - 2021-05-08 11:21:16,243 - Bad Request: /api/change_password
- WARNING - 2021-05-08 11:21:21,542 - Bad Request: /api/login
- WARNING - 2021-05-08 12:13:32,209 - Unauthorized: /api/user
- WARNING - 2021-05-08 12:13:32,213 - Unauthorized: /api/login_history
- INFO - 2021-05-08 12:23:09,980 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- WARNING - 2021-05-08 12:24:51,280 - Unauthorized: /api/user
- WARNING - 2021-05-08 12:24:51,282 - Unauthorized: /api/login_history
- WARNING - 2021-05-08 12:25:17,616 - Bad Request: /api/change_password
- WARNING - 2021-05-08 12:26:34,610 - Bad Request: /api/change_password
- WARNING - 2021-05-08 12:26:41,420 - Bad Request: /api/change_password
- WARNING - 2021-05-08 12:26:44,416 - Bad Request: /api/change_password
- WARNING - 2021-05-08 12:26:50,798 - Bad Request: /api/change_password
- WARNING - 2021-05-08 12:26:59,471 - Bad Request: /api/change_password
- WARNING - 2021-05-08 12:27:25,646 - Bad Request: /api/change_password
- WARNING - 2021-05-08 12:27:44,446 - Bad Request: /api/login
- WARNING - 2021-05-08 13:20:23,955 - Bad Request: /api/test
- INFO - 2021-05-08 13:20:52,815 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- ERROR - 2021-05-08 13:21:34,773 - Internal Server Error: /api/test
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py", line 208, in post
    }, status=status.HTTP_200_OK)
  File "C:\Python37\lib\site-packages\django\http\response.py", line 603, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "C:\Python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Python37\lib\site-packages\django\core\serializers\json.py", line 105, in default
    return super().default(o)
  File "C:\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type InMemoryUploadedFile is not JSON serializable
- ERROR - 2021-05-08 13:22:21,522 - Internal Server Error: /api/test
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py", line 208, in post
    }, status=status.HTTP_200_OK)
  File "C:\Python37\lib\site-packages\django\http\response.py", line 603, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "C:\Python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Python37\lib\site-packages\django\core\serializers\json.py", line 105, in default
    return super().default(o)
  File "C:\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type InMemoryUploadedFile is not JSON serializable
- INFO - 2021-05-08 13:22:21,617 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- ERROR - 2021-05-08 13:23:05,768 - Internal Server Error: /api/test
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py", line 208, in post
    }, status=status.HTTP_200_OK)
  File "C:\Python37\lib\site-packages\django\http\response.py", line 603, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "C:\Python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Python37\lib\site-packages\django\core\serializers\json.py", line 105, in default
    return super().default(o)
  File "C:\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type InMemoryUploadedFile is not JSON serializable
- INFO - 2021-05-08 13:23:20,882 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-08 13:24:00,311 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-08 13:24:36,110 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-08 13:29:18,853 - D:\GitHub\secure-file-storage-app\api\file_manager\file\urls.py changed, reloading.
- INFO - 2021-05-08 13:33:04,268 - Init Server
- INFO - 2021-05-08 13:33:04,273 - access_token is expired. Now: 2021-05-08 06:33:04.272114, token_expiry: 2021-05-07 15:56:55
- INFO - 2021-05-08 13:33:04,278 - access_token is expired. Now: 2021-05-08 06:33:04.278114, token_expiry: 2021-05-07 15:56:55
- INFO - 2021-05-08 13:36:12,715 - Init Server
- INFO - 2021-05-08 13:36:12,785 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-08 13:36:14,145 - get_file_list
- INFO - 2021-05-08 13:36:14,145 - get_content_file -> (file : 1s21uBO0G69wc_FyB_BASX-6AaLas5VQn - map.json)
- ERROR - 2021-05-08 13:36:15,675 - Internal Server Error: /api/sync_file
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 426, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
- INFO - 2021-05-08 13:38:18,978 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-08 13:38:48,893 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-08 13:39:32,167 - Init Server
- INFO - 2021-05-08 13:39:32,238 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-08 13:39:33,519 - get_file_list
- INFO - 2021-05-08 13:39:33,520 - get_content_file -> (file : 1s21uBO0G69wc_FyB_BASX-6AaLas5VQn - map.json)
- ERROR - 2021-05-08 13:39:35,106 - Internal Server Error: /api/sync_file
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 426, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
- INFO - 2021-05-08 13:40:35,474 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-08 13:41:46,027 - Init Server
- INFO - 2021-05-08 13:41:46,086 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-08 13:41:47,307 - get_file_list
- INFO - 2021-05-08 13:41:47,308 - get_content_file -> (file : 1s21uBO0G69wc_FyB_BASX-6AaLas5VQn - map.json)
- ERROR - 2021-05-08 13:41:48,812 - Internal Server Error: /api/sync_file
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 426, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
- INFO - 2021-05-08 13:42:27,078 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-08 13:43:01,311 - Init Server
- INFO - 2021-05-08 13:43:01,397 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-08 13:43:02,775 - get_file_list
- INFO - 2021-05-08 13:43:02,796 - get_content_file -> (file : 1s21uBO0G69wc_FyB_BASX-6AaLas5VQn - map.json)
- ERROR - 2021-05-08 13:43:04,233 - Internal Server Error: /api/sync_file
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 426, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
- INFO - 2021-05-08 13:43:32,046 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-08 13:44:13,438 - Init Server
- INFO - 2021-05-08 13:44:13,520 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-08 13:44:15,564 - get_file_list
- INFO - 2021-05-08 13:44:15,564 - get_content_file -> (file : 1s21uBO0G69wc_FyB_BASX-6AaLas5VQn - map.json)
- ERROR - 2021-05-08 13:44:17,078 - Internal Server Error: /api/sync_file
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 426, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
- INFO - 2021-05-08 13:44:38,940 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-08 13:44:52,454 - Init Server
- INFO - 2021-05-08 13:44:52,496 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-08 13:44:53,822 - get_file_list
- INFO - 2021-05-08 13:44:53,866 - get_content_file -> (file : 1s21uBO0G69wc_FyB_BASX-6AaLas5VQn - map.json)
- ERROR - 2021-05-08 13:44:55,072 - Internal Server Error: /api/sync_file
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 426, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
- INFO - 2021-05-08 13:45:13,707 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-08 13:45:29,710 - Init Server
- INFO - 2021-05-08 13:45:29,753 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-08 13:45:30,967 - get_file_list
- INFO - 2021-05-08 13:45:30,969 - get_content_file -> (file : 1s21uBO0G69wc_FyB_BASX-6AaLas5VQn - map.json)
- ERROR - 2021-05-08 13:45:32,321 - Internal Server Error: /api/sync_file
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 426, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
- INFO - 2021-05-08 13:45:53,981 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-08 13:46:07,706 - Init Server
- INFO - 2021-05-08 13:46:07,748 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-08 13:46:08,971 - get_file_list
- INFO - 2021-05-08 13:46:08,971 - get_content_file -> (file : 1s21uBO0G69wc_FyB_BASX-6AaLas5VQn - map.json)
- ERROR - 2021-05-08 13:46:10,239 - Internal Server Error: /api/sync_file
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 426, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
- INFO - 2021-05-08 13:46:26,271 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-08 13:46:42,703 - Init Server
- INFO - 2021-05-08 13:46:42,753 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-08 13:46:44,353 - get_file_list
- INFO - 2021-05-08 13:46:44,353 - get_content_file -> (file : 1s21uBO0G69wc_FyB_BASX-6AaLas5VQn - map.json)
- ERROR - 2021-05-08 13:46:45,791 - Internal Server Error: /api/sync_file
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 426, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
- INFO - 2021-05-08 13:46:57,994 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-08 13:48:19,640 - Init Server
- INFO - 2021-05-08 13:48:19,709 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-08 13:48:20,997 - get_file_list
- INFO - 2021-05-08 13:48:20,997 - get_content_file -> (file : 1s21uBO0G69wc_FyB_BASX-6AaLas5VQn - map.json)
- ERROR - 2021-05-08 13:48:22,611 - Internal Server Error: /api/sync_file
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 426, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
- INFO - 2021-05-08 13:49:09,480 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-08 13:49:59,105 - Init Server
- INFO - 2021-05-08 13:49:59,172 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-08 13:50:00,455 - get_file_list
- INFO - 2021-05-08 13:50:00,455 - get_content_file -> (file : 1s21uBO0G69wc_FyB_BASX-6AaLas5VQn - map.json)
- WARNING - 2021-05-08 13:50:01,711 - Bad Request: /api/sync_file
- INFO - 2021-05-08 13:52:43,794 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-08 13:53:05,673 - Init Server
- INFO - 2021-05-08 13:53:05,759 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-08 13:53:07,061 - get_file_list
- INFO - 2021-05-08 13:53:07,062 - get_content_file -> (file : 1s21uBO0G69wc_FyB_BASX-6AaLas5VQn - map.json)
- WARNING - 2021-05-08 13:53:08,200 - Bad Request: /api/sync_file
- WARNING - 2021-05-08 14:06:09,760 - Unauthorized: /api/user
- WARNING - 2021-05-08 14:06:09,764 - Unauthorized: /api/login_history
- INFO - 2021-05-08 14:06:37,515 - Init Server
- INFO - 2021-05-08 14:06:37,550 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-08 14:06:38,977 - get_file_list
- INFO - 2021-05-08 14:06:38,977 - get_content_file -> (file : 1s21uBO0G69wc_FyB_BASX-6AaLas5VQn - map.json)
- WARNING - 2021-05-08 14:06:40,052 - Bad Request: /api/sync_file
- INFO - 2021-05-08 14:07:16,653 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-08 14:07:58,365 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-08 14:09:27,159 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-08 14:10:21,401 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-08 14:11:40,471 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-08 14:12:55,150 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-08 14:13:55,740 - Init Server
- INFO - 2021-05-08 14:13:55,817 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-08 14:13:57,087 - get_file_list
- INFO - 2021-05-08 14:13:57,087 - get_content_file -> (file : 1s21uBO0G69wc_FyB_BASX-6AaLas5VQn - map.json)
- WARNING - 2021-05-08 14:13:58,259 - Bad Request: /api/sync_file
- WARNING - 2021-05-08 14:14:39,930 - Unauthorized: /api/user
- WARNING - 2021-05-08 14:14:39,933 - Unauthorized: /api/login_history
- INFO - 2021-05-08 14:18:45,932 - Init Server
- INFO - 2021-05-08 14:18:45,971 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-08 14:18:47,315 - get_file_list
- INFO - 2021-05-08 14:18:47,316 - get_content_file -> (file : 1s21uBO0G69wc_FyB_BASX-6AaLas5VQn - map.json)
- WARNING - 2021-05-08 14:18:48,295 - Bad Request: /api/sync_file
- INFO - 2021-05-08 14:19:36,370 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-08 14:20:03,818 - Init Server
- INFO - 2021-05-08 14:20:03,901 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-08 14:20:05,214 - get_file_list
- INFO - 2021-05-08 14:20:05,214 - get_content_file -> (file : 1s21uBO0G69wc_FyB_BASX-6AaLas5VQn - map.json)
- WARNING - 2021-05-08 14:22:04,443 - Unauthorized: /api/user
- WARNING - 2021-05-08 14:22:04,450 - Unauthorized: /api/login_history
- INFO - 2021-05-08 14:24:36,000 - Init Server
- INFO - 2021-05-08 14:24:36,035 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-08 14:24:37,349 - get_file_list
- INFO - 2021-05-08 14:24:37,349 - get_content_file -> (file : 1s21uBO0G69wc_FyB_BASX-6AaLas5VQn - map.json)
- INFO - 2021-05-08 14:31:39,790 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-08 14:32:13,224 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-08 14:33:49,662 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- WARNING - 2021-05-08 14:35:48,506 - Unauthorized: /api/sync_file
- INFO - 2021-05-08 14:37:48,921 - Init Server
- INFO - 2021-05-08 14:37:48,922 - access_token is expired. Now: 2021-05-08 07:37:48.922303, token_expiry: 2021-05-08 07:33:31
- INFO - 2021-05-08 14:37:48,928 - access_token is expired. Now: 2021-05-08 07:37:48.928304, token_expiry: 2021-05-08 07:33:31
- INFO - 2021-05-08 14:39:10,955 - Init Server
- INFO - 2021-05-08 14:39:11,040 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-08 14:39:12,640 - get_file_list
- INFO - 2021-05-08 14:39:12,641 - get_content_file -> (file : 1s21uBO0G69wc_FyB_BASX-6AaLas5VQn - map.json)
- INFO - 2021-05-08 14:40:34,770 - Init Server
- INFO - 2021-05-08 14:40:34,794 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-08 14:40:36,076 - get_file_list
- INFO - 2021-05-08 14:40:36,076 - get_content_file -> (file : 1s21uBO0G69wc_FyB_BASX-6AaLas5VQn - map.json)
- INFO - 2021-05-08 14:40:38,288 - Init Server
- INFO - 2021-05-08 14:40:38,290 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-08 14:40:39,462 - get_file_list
- INFO - 2021-05-08 14:40:39,462 - get_content_file -> (file : 1s21uBO0G69wc_FyB_BASX-6AaLas5VQn - map.json)
- INFO - 2021-05-08 14:41:14,739 - Init Server
- INFO - 2021-05-08 14:41:14,743 - Init Server
- INFO - 2021-05-08 14:41:14,768 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-08 14:41:14,770 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-08 14:41:16,048 - get_file_list
- INFO - 2021-05-08 14:41:16,048 - get_content_file -> (file : 1s21uBO0G69wc_FyB_BASX-6AaLas5VQn - map.json)
- INFO - 2021-05-08 14:41:16,059 - get_file_list
- INFO - 2021-05-08 14:41:16,059 - get_content_file -> (file : 1s21uBO0G69wc_FyB_BASX-6AaLas5VQn - map.json)
- INFO - 2021-05-08 14:44:06,185 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-08 14:47:22,050 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-08 14:48:10,838 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-08 14:49:01,228 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-08 14:50:10,769 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-08 14:50:30,200 - Init Server
- INFO - 2021-05-08 14:50:30,263 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-08 14:50:31,489 - get_file_list
- INFO - 2021-05-08 14:50:31,490 - get_content_file -> (file : 1s21uBO0G69wc_FyB_BASX-6AaLas5VQn - map.json)
- INFO - 2021-05-08 14:51:31,500 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-08 14:51:53,367 - Init Server
- INFO - 2021-05-08 14:51:53,432 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-08 14:51:54,634 - get_file_list
- INFO - 2021-05-08 14:51:54,635 - get_content_file -> (file : 1s21uBO0G69wc_FyB_BASX-6AaLas5VQn - map.json)
- INFO - 2021-05-08 15:18:36,985 - Init Server
- INFO - 2021-05-08 15:18:37,022 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-08 15:18:38,548 - get_file_list
- INFO - 2021-05-08 15:18:38,548 - get_content_file -> (file : 1s21uBO0G69wc_FyB_BASX-6AaLas5VQn - map.json)
- WARNING - 2021-05-08 16:59:26,830 - Unauthorized: /api/sync_file
- WARNING - 2021-05-11 11:31:08,269 - Not Found: /
- WARNING - 2021-05-11 11:31:09,864 - Not Found: /favicon.ico
- INFO - 2021-05-11 11:36:51,055 - Init Server
- INFO - 2021-05-11 11:36:51,055 - access_token is expired. Now: 2021-05-11 04:36:51.055933, token_expiry: 2021-05-08 08:38:18
- INFO - 2021-05-11 11:36:51,060 - access_token is expired. Now: 2021-05-11 04:36:51.060934, token_expiry: 2021-05-08 08:38:18
- WARNING - 2021-05-11 11:38:36,359 - Bad Request: /api/register
- INFO - 2021-05-11 11:38:59,202 - Init Server
- INFO - 2021-05-11 11:38:59,248 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-11 11:39:26,755 - Init Server
- INFO - 2021-05-11 11:39:26,783 - file_cache is only supported with oauth2client<4.0.0
- WARNING - 2021-05-11 11:40:31,521 - Unauthorized: /api/login_history
- WARNING - 2021-05-11 11:40:31,517 - Unauthorized: /api/user
- WARNING - 2021-05-11 11:43:19,215 - Unauthorized: /api/user
- WARNING - 2021-05-11 11:43:19,219 - Unauthorized: /api/login_history
- INFO - 2021-05-11 11:49:14,574 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- WARNING - 2021-05-11 11:59:41,334 - Bad Request: /api/login
- WARNING - 2021-05-11 12:00:51,953 - Bad Request: /api/change_password
- WARNING - 2021-05-11 12:53:30,682 - Unauthorized: /api/user
- WARNING - 2021-05-11 12:53:30,688 - Unauthorized: /api/login_history
- INFO - 2021-05-11 13:03:50,165 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- WARNING - 2021-05-13 09:07:15,834 - Not Found: /
- WARNING - 2021-05-13 09:07:17,686 - Not Found: /favicon.ico
- INFO - 2021-05-13 09:07:49,222 - Init Server
- INFO - 2021-05-13 09:07:49,299 - file_cache is only supported with oauth2client<4.0.0
- WARNING - 2021-05-13 09:11:19,420 - Unauthorized: /api/user
- WARNING - 2021-05-13 09:11:19,423 - Unauthorized: /api/login_history
- INFO - 2021-05-13 09:13:29,726 - Init Server
- INFO - 2021-05-13 09:13:29,751 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-13 09:13:31,341 - get_file_list
- INFO - 2021-05-13 09:13:31,341 - get_content_file -> (file : 1s21uBO0G69wc_FyB_BASX-6AaLas5VQn - map.json)
- INFO - 2021-05-13 09:13:32,406 - Init Server
- INFO - 2021-05-13 09:13:32,409 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-13 09:13:33,746 - get_file_list
- INFO - 2021-05-13 09:13:33,747 - get_content_file -> (file : 1s21uBO0G69wc_FyB_BASX-6AaLas5VQn - map.json)
- INFO - 2021-05-13 09:17:55,237 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-13 09:20:46,585 - D:\GitHub\secure-file-storage-app\api\file_manager\file_storage\file_storage.py changed, reloading.
- INFO - 2021-05-13 09:22:09,455 - D:\GitHub\secure-file-storage-app\api\file_manager\file_storage\file_storage.py changed, reloading.
- INFO - 2021-05-13 09:23:02,174 - Init Server
- INFO - 2021-05-13 09:23:18,461 - Init Server
- INFO - 2021-05-13 09:23:46,017 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-13 09:23:47,559 - get_file_list
- INFO - 2021-05-13 09:23:55,260 - get_file_list
- INFO - 2021-05-13 09:24:47,311 - get_file_list
- INFO - 2021-05-13 09:25:56,881 - D:\GitHub\secure-file-storage-app\api\file_manager\file_storage\file_storage.py changed, reloading.
- INFO - 2021-05-13 09:26:40,503 - get_files_by_title -> (title: Algorithm PD.docx.aes)
- INFO - 2021-05-13 09:27:02,450 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-13 09:27:44,033 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-13 09:29:58,665 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-13 09:30:32,929 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-13 09:30:57,427 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-13 09:31:38,075 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-13 09:32:06,219 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-13 09:32:40,705 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-13 09:33:15,389 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-13 09:34:28,932 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- WARNING - 2021-05-13 09:37:49,401 - Unauthorized: /api/login_history
- WARNING - 2021-05-13 09:37:49,402 - Unauthorized: /api/user
- INFO - 2021-05-13 09:38:06,263 - Init Server
- INFO - 2021-05-13 09:38:06,339 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-13 09:38:07,843 - get_file_list
- INFO - 2021-05-13 09:38:07,843 - get_content_file -> (file : 1s21uBO0G69wc_FyB_BASX-6AaLas5VQn - map.json)
- INFO - 2021-05-13 09:38:47,638 - Init Server
- INFO - 2021-05-13 09:38:47,667 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-13 09:38:50,831 - upload_file -> (file_name: 000028github.com_Merevoli-DatLuu_MST_blob_main_main.cpp (1).png.aes)
- WARNING - 2021-05-13 09:39:39,201 - Bad Request: /api/file
- INFO - 2021-05-13 09:40:14,755 - Init Server
- INFO - 2021-05-13 09:40:14,779 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-13 09:40:16,312 - get_file_list
- INFO - 2021-05-13 09:40:16,312 - get_content_file -> (file : 1s21uBO0G69wc_FyB_BASX-6AaLas5VQn - map.json)
- WARNING - 2021-05-13 09:40:47,374 - Method Not Allowed: /api/remove_file
- INFO - 2021-05-13 09:42:31,451 - Init Server
- INFO - 2021-05-13 09:42:31,492 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-13 09:42:32,702 - get_file_list
- INFO - 2021-05-13 09:42:32,702 - get_content_file -> (file : 1s21uBO0G69wc_FyB_BASX-6AaLas5VQn - map.json)
- WARNING - 2021-05-13 09:42:39,148 - Unauthorized: /api/remove_file
- INFO - 2021-05-13 09:43:31,825 - Init Server
- INFO - 2021-05-13 09:43:31,866 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-13 09:43:33,135 - get_file_list
- INFO - 2021-05-13 09:43:33,135 - get_content_file -> (file : 1s21uBO0G69wc_FyB_BASX-6AaLas5VQn - map.json)
- WARNING - 2021-05-13 09:43:44,427 - Bad Request: /api/remove_file
- WARNING - 2021-05-13 09:44:10,829 - Bad Request: /api/remove_file
- WARNING - 2021-05-13 09:45:36,997 - Bad Request: /api/remove_file
- WARNING - 2021-05-13 09:45:52,509 - Bad Request: /api/remove_file
- WARNING - 2021-05-13 09:48:07,668 - Not Found: /api/remove_files
- INFO - 2021-05-13 09:48:45,895 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-13 09:49:15,063 - Init Server
- INFO - 2021-05-13 09:49:15,111 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-13 09:49:16,409 - get_file_list
- INFO - 2021-05-13 09:49:16,410 - get_content_file -> (file : 1s21uBO0G69wc_FyB_BASX-6AaLas5VQn - map.json)
- WARNING - 2021-05-13 09:49:27,396 - Unauthorized: /api/remove_file
- WARNING - 2021-05-13 09:50:00,868 - Unauthorized: /api/remove_file
- WARNING - 2021-05-13 09:50:51,839 - Unauthorized: /api/remove_file
- WARNING - 2021-05-13 09:53:42,080 - Unauthorized: /api/remove_file
- INFO - 2021-05-13 09:55:13,577 - Init Server
- INFO - 2021-05-13 09:55:13,609 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-13 09:55:14,909 - get_file_list
- INFO - 2021-05-13 09:55:14,910 - get_file_by_id -> (file_id: 1XEs9xN2DlXBIPSg1m1ybGGmRdeWPrD2n)
- INFO - 2021-05-13 09:55:15,817 - delete_file_by_id -> (file_id: 1XEs9xN2DlXBIPSg1m1ybGGmRdeWPrD2n)
- INFO - 2021-05-13 09:57:48,684 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-13 09:58:39,188 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-13 09:59:47,315 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-13 10:00:13,680 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-13 10:00:40,437 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-13 10:01:24,857 - D:\GitHub\secure-file-storage-app\api\file_manager\file\urls.py changed, reloading.
- INFO - 2021-05-13 12:04:46,068 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- WARNING - 2021-05-13 12:07:39,589 - Unauthorized: /api/user
- WARNING - 2021-05-13 12:07:39,591 - Unauthorized: /api/login_history
- WARNING - 2021-05-13 12:08:43,575 - Unauthorized: /api/user
- WARNING - 2021-05-13 12:08:43,580 - Unauthorized: /api/login_history
- WARNING - 2021-05-13 12:09:20,711 - Unauthorized: /api/file
- INFO - 2021-05-13 12:09:50,193 - Init Server
- INFO - 2021-05-13 12:09:50,260 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-13 12:09:53,337 - upload_file -> (file_name: 000004contents (1).txt.aes)
- INFO - 2021-05-13 12:13:12,765 - Init Server
- INFO - 2021-05-13 12:13:12,800 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-13 12:13:15,569 - upload_file -> (file_name: 000004contents (1).txt.aes)
- INFO - 2021-05-13 12:14:50,761 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-13 12:15:32,634 - Init Server
- INFO - 2021-05-13 12:15:32,708 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-13 12:15:33,942 - get_file_list
- INFO - 2021-05-13 12:15:33,943 - get_file_by_id -> (file_id: 1_FDoMKt9lKxr8Rn9Oex1zY7G49uAF0wK)
- INFO - 2021-05-13 12:15:34,843 - delete_file_by_id -> (file_id: 1_FDoMKt9lKxr8Rn9Oex1zY7G49uAF0wK)
- INFO - 2021-05-13 12:15:47,260 - Init Server
- INFO - 2021-05-13 12:15:47,278 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-13 12:15:48,468 - get_file_list
- INFO - 2021-05-13 12:15:48,468 - get_file_by_id -> (file_id: 13wAWcf-Ixefq12NxlQlPKMy87g9-4y7h)
- INFO - 2021-05-13 12:15:49,211 - delete_file_by_id -> (file_id: 13wAWcf-Ixefq12NxlQlPKMy87g9-4y7h)
- INFO - 2021-05-13 12:16:06,560 - Init Server
- INFO - 2021-05-13 12:16:06,592 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-13 12:16:09,152 - upload_file -> (file_name: 000004contents (1).txt.aes)
- INFO - 2021-05-13 12:18:03,636 - Init Server
- INFO - 2021-05-13 12:18:03,677 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-13 12:18:06,544 - upload_file -> (file_name: 000004contents (1).txt.aes)
- INFO - 2021-05-13 12:21:44,361 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-13 12:22:27,534 - Init Server
- INFO - 2021-05-13 12:22:27,609 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-13 12:22:30,056 - upload_file -> (file_name: 000004contents (1).txt.aes)
- INFO - 2021-05-13 12:24:10,644 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- WARNING - 2021-05-13 12:25:15,073 - Method Not Allowed: /api/update_file
- INFO - 2021-05-13 12:25:45,645 - Init Server
- INFO - 2021-05-13 12:25:45,694 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-13 12:25:46,975 - get_file_list
- INFO - 2021-05-13 12:25:46,978 - get_file_by_id -> (file_id: 1AGPFPTD8J1SAUAZuXE_2maHKUWuqGtXk)
- INFO - 2021-05-13 12:25:47,947 - delete_file_by_id -> (file_id: 1AGPFPTD8J1SAUAZuXE_2maHKUWuqGtXk)
- INFO - 2021-05-13 12:25:50,797 - upload_file -> (file_name: 000004contents (1).txt.aes)
- INFO - 2021-05-13 12:27:39,757 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-13 12:28:08,326 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-13 12:28:33,879 - D:\GitHub\secure-file-storage-app\api\file_manager\file\urls.py changed, reloading.
- INFO - 2021-05-13 12:31:24,345 - Init Server
- INFO - 2021-05-13 12:31:24,407 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-13 12:31:25,949 - get_file_list
- INFO - 2021-05-13 12:31:25,950 - get_file_by_id -> (file_id: 1s21uBO0G69wc_FyB_BASX-6AaLas5VQn)
- INFO - 2021-05-13 12:31:26,928 - delete_file_by_id -> (file_id: 1s21uBO0G69wc_FyB_BASX-6AaLas5VQn)
- INFO - 2021-05-13 12:31:29,317 - upload_file -> (file_name: map.json)
- INFO - 2021-05-13 12:36:28,031 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-13 12:48:20,439 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-13 12:51:32,647 - Init Server
- INFO - 2021-05-13 12:51:32,735 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-13 12:51:33,411 - get_files_by_title -> (title: map.json)
- INFO - 2021-05-13 12:51:33,412 - get_content_file -> (file : 1vZKt2pjJocNFW0P1ZYlHpgEWeZVeQJgX - map.json)
- INFO - 2021-05-13 12:51:35,277 - get_files_by_title -> (title: 000004contents (1).txt.aes)
- INFO - 2021-05-13 12:51:36,477 - download_file -> (file_name: .temp/000004contents (1).txt.aes)
- WARNING - 2021-05-13 13:24:41,970 - Unauthorized: /api/user
- WARNING - 2021-05-13 13:24:41,973 - Unauthorized: /api/login_history
- INFO - 2021-05-13 13:26:08,726 - Init Server
- INFO - 2021-05-13 13:26:08,755 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-13 13:26:09,365 - get_files_by_title -> (title: map.json)
- INFO - 2021-05-13 13:26:09,365 - get_content_file -> (file : 1vZKt2pjJocNFW0P1ZYlHpgEWeZVeQJgX - map.json)
- INFO - 2021-05-13 13:26:11,175 - get_files_by_title -> (title: 000004contents (1).txt.aes)
- INFO - 2021-05-13 13:26:12,268 - download_file -> (file_name: .temp/000004contents (1).txt.aes)
- INFO - 2021-05-13 13:27:09,126 - Init Server
- INFO - 2021-05-13 13:27:09,155 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-13 13:27:09,755 - get_files_by_title -> (title: map.json)
- INFO - 2021-05-13 13:27:09,755 - get_content_file -> (file : 1vZKt2pjJocNFW0P1ZYlHpgEWeZVeQJgX - map.json)
- INFO - 2021-05-13 13:27:11,523 - get_files_by_title -> (title: 000004contents (1).txt.aes)
- INFO - 2021-05-13 13:27:12,778 - download_file -> (file_name: .temp/000004contents (1).txt.aes)
- INFO - 2021-05-13 13:28:20,145 - Init Server
- INFO - 2021-05-13 13:28:20,167 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-13 13:28:20,752 - get_files_by_title -> (title: map.json)
- INFO - 2021-05-13 13:28:20,753 - get_content_file -> (file : 1vZKt2pjJocNFW0P1ZYlHpgEWeZVeQJgX - map.json)
- INFO - 2021-05-13 13:28:22,632 - get_files_by_title -> (title: 000004contents (1).txt.aes)
- INFO - 2021-05-13 13:28:23,673 - download_file -> (file_name: .temp/000004contents (1).txt.aes)
- INFO - 2021-05-13 13:28:42,320 - Init Server
- INFO - 2021-05-13 13:28:42,349 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-13 13:28:43,001 - get_files_by_title -> (title: map.json)
- INFO - 2021-05-13 13:28:43,001 - get_content_file -> (file : 1vZKt2pjJocNFW0P1ZYlHpgEWeZVeQJgX - map.json)
- INFO - 2021-05-13 13:28:44,709 - get_files_by_title -> (title: 000004contents (1).txt.aes)
- INFO - 2021-05-13 13:28:46,019 - download_file -> (file_name: .temp/000004contents (1).txt.aes)
- INFO - 2021-05-13 13:30:04,322 - Init Server
- INFO - 2021-05-13 13:30:04,366 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-13 13:30:05,097 - get_files_by_title -> (title: map.json)
- INFO - 2021-05-13 13:30:05,097 - get_content_file -> (file : 1vZKt2pjJocNFW0P1ZYlHpgEWeZVeQJgX - map.json)
- INFO - 2021-05-13 13:30:06,893 - get_files_by_title -> (title: 000004contents (1).txt.aes)
- INFO - 2021-05-13 13:30:08,095 - download_file -> (file_name: .temp/000004contents (1).txt.aes)
- INFO - 2021-05-13 13:30:46,757 - Init Server
- INFO - 2021-05-13 13:30:46,790 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-13 13:30:47,718 - get_files_by_title -> (title: map.json)
- INFO - 2021-05-13 13:30:47,718 - get_content_file -> (file : 1vZKt2pjJocNFW0P1ZYlHpgEWeZVeQJgX - map.json)
- INFO - 2021-05-13 13:30:49,547 - get_files_by_title -> (title: 000004contents (1).txt.aes)
- INFO - 2021-05-13 13:30:50,681 - download_file -> (file_name: .temp/000004contents (1).txt.aes)
- INFO - 2021-05-13 13:31:47,999 - Init Server
- INFO - 2021-05-13 13:31:48,045 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-13 13:31:48,743 - get_files_by_title -> (title: map.json)
- INFO - 2021-05-13 13:31:48,743 - get_content_file -> (file : 1vZKt2pjJocNFW0P1ZYlHpgEWeZVeQJgX - map.json)
- INFO - 2021-05-13 13:31:50,489 - get_files_by_title -> (title: 000004contents (1).txt.aes)
- INFO - 2021-05-13 13:31:51,671 - download_file -> (file_name: .temp/000004contents (1).txt.aes)
- INFO - 2021-05-13 13:32:09,355 - Init Server
- INFO - 2021-05-13 13:32:09,396 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-13 13:32:10,086 - get_files_by_title -> (title: map.json)
- INFO - 2021-05-13 13:32:10,086 - get_content_file -> (file : 1vZKt2pjJocNFW0P1ZYlHpgEWeZVeQJgX - map.json)
- INFO - 2021-05-13 13:32:11,865 - get_files_by_title -> (title: 000004contents (1).txt.aes)
- INFO - 2021-05-13 13:32:12,989 - download_file -> (file_name: .temp/000004contents (1).txt.aes)
- WARNING - 2021-05-13 13:32:48,999 - Unauthorized: /api/user
- WARNING - 2021-05-13 13:32:49,003 - Unauthorized: /api/login_history
- INFO - 2021-05-13 13:38:06,378 - Init Server
- INFO - 2021-05-13 13:38:06,423 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-13 13:38:07,185 - get_files_by_title -> (title: map.json)
- INFO - 2021-05-13 13:38:07,185 - get_content_file -> (file : 1vZKt2pjJocNFW0P1ZYlHpgEWeZVeQJgX - map.json)
- INFO - 2021-05-13 13:38:08,829 - get_files_by_title -> (title: 000004contents (1).txt.aes)
- INFO - 2021-05-13 13:38:09,984 - download_file -> (file_name: .temp/000004contents (1).txt.aes)
- INFO - 2021-05-13 13:38:37,009 - Init Server
- INFO - 2021-05-13 13:38:37,038 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-13 13:38:37,592 - get_files_by_title -> (title: map.json)
- INFO - 2021-05-13 13:38:37,593 - get_content_file -> (file : 1vZKt2pjJocNFW0P1ZYlHpgEWeZVeQJgX - map.json)
- INFO - 2021-05-13 13:38:39,144 - get_files_by_title -> (title: 000004contents (1).txt.aes)
- INFO - 2021-05-13 13:38:40,234 - download_file -> (file_name: .temp/000004contents (1).txt.aes)
- INFO - 2021-05-13 13:43:05,235 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-13 13:43:56,136 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-13 13:46:00,885 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-13 13:46:38,736 - D:\GitHub\secure-file-storage-app\api\file_manager\file\urls.py changed, reloading.
- INFO - 2021-05-13 13:47:11,680 - D:\GitHub\secure-file-storage-app\api\file_manager\file\urls.py changed, reloading.
- INFO - 2021-05-13 13:49:06,737 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- ERROR - 2021-05-13 13:51:08,113 - Internal Server Error: /api/file/map
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py", line 115, in get
    file_id = kwargs['file_id']
KeyError: 'file_id'
- INFO - 2021-05-13 13:51:47,947 - D:\GitHub\secure-file-storage-app\api\file_manager\file\urls.py changed, reloading.
- ERROR - 2021-05-13 13:52:12,307 - Internal Server Error: /api/file_map
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py", line 115, in get
    file_id = kwargs['file_id']
KeyError: 'file_id'
- INFO - 2021-05-13 13:53:12,001 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- INFO - 2021-05-13 13:53:47,428 - Init Server
- ERROR - 2021-05-13 13:53:47,687 - Internal Server Error: /api/file/map
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py", line 119, in get
    files = file_storage.get_files_by_title_in_specific_folder(file_name, request.user.email)
AttributeError: 'AnonymousUser' object has no attribute 'email'
- INFO - 2021-05-13 13:54:31,406 - D:\GitHub\secure-file-storage-app\api\file_manager\file\views.py changed, reloading.
- WARNING - 2021-05-13 13:55:04,190 - Unauthorized: /api/file/map
- WARNING - 2021-05-13 13:55:35,357 - Unauthorized: /api/file/map
- INFO - 2021-05-13 13:57:20,834 - Init Server
- INFO - 2021-05-13 13:57:20,908 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-13 13:57:22,227 - get_files_by_title -> (title: map.json)
- INFO - 2021-05-13 13:57:23,228 - download_file -> (file_name: .temp/map.json)
- INFO - 2021-05-13 21:15:22,725 - Init Server
- INFO - 2021-05-13 21:15:22,734 - file_cache is only supported with oauth2client<4.0.0
- ERROR - 2021-05-13 21:15:26,009 - Internal Server Error: /api/register
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py", line 52, in post
    json.dumps(data_map, map_file)
TypeError: dumps() takes 1 positional argument but 2 were given
- WARNING - 2021-05-13 21:15:26,197 - Bad Request: /api/register
- INFO - 2021-05-13 21:16:06,320 - Init Server
- INFO - 2021-05-13 21:16:06,338 - file_cache is only supported with oauth2client<4.0.0
- ERROR - 2021-05-13 21:16:09,344 - Internal Server Error: /api/register
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py", line 52, in post
    json.dumps(data_map, map_file)
TypeError: dumps() takes 1 positional argument but 2 were given
- INFO - 2021-05-13 21:16:48,837 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- INFO - 2021-05-13 21:17:31,857 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- INFO - 2021-05-13 21:18:06,799 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- INFO - 2021-05-13 21:19:01,970 - Init Server
- INFO - 2021-05-13 21:19:02,072 - file_cache is only supported with oauth2client<4.0.0
- WARNING - 2021-05-13 21:19:05,778 - Bad Request: /api/register
- ERROR - 2021-05-13 21:19:05,986 - Internal Server Error: /api/register
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py", line 52, in post
    map_file = open(file_path, 'w')
FileNotFoundError: [Errno 2] No such file or directory: '.temp/test12@fm.com/map.json'
- INFO - 2021-05-13 21:20:32,572 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- INFO - 2021-05-13 21:21:13,846 - Init Server
- INFO - 2021-05-13 21:21:13,900 - file_cache is only supported with oauth2client<4.0.0
- ERROR - 2021-05-13 21:21:16,949 - Internal Server Error: /api/register
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py", line 53, in post
    file_path = base_dir + email_info + "/map.json"
FileNotFoundError: [Errno 2] No such file or directory: '.temp/test12@fm.com/map.json'
- INFO - 2021-05-13 21:23:56,969 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- INFO - 2021-05-13 21:24:31,067 - D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py changed, reloading.
- INFO - 2021-05-13 21:25:25,251 - Init Server
- INFO - 2021-05-13 21:25:25,342 - file_cache is only supported with oauth2client<4.0.0
- ERROR - 2021-05-13 21:25:28,388 - Internal Server Error: /api/register
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py", line 61, in post
AttributeError: 'AnonymousUser' object has no attribute 'email'
- INFO - 2021-05-13 21:28:43,480 - Init Server
- INFO - 2021-05-13 21:28:43,503 - file_cache is only supported with oauth2client<4.0.0
- ERROR - 2021-05-13 21:28:46,502 - Internal Server Error: /api/register
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python37\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\GitHub\secure-file-storage-app\api\file_manager\user\views.py", line 61, in post
    file_storage.upload_file_with_path_in_specific_folder(file_path, email_info)
AttributeError: 'AnonymousUser' object has no attribute 'email'
- WARNING - 2021-05-13 21:28:46,880 - Bad Request: /api/register
- INFO - 2021-05-13 21:32:50,446 - Init Server
- INFO - 2021-05-13 21:32:50,516 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-13 21:32:55,802 - upload_file -> (file_name: map.json)
- INFO - 2021-05-13 21:35:53,941 - Init Server
- INFO - 2021-05-13 21:35:53,968 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-13 21:35:58,942 - upload_file -> (file_name: map.json)
- WARNING - 2021-05-13 21:36:24,161 - Unauthorized: /api/user
- WARNING - 2021-05-13 21:36:24,171 - Unauthorized: /api/login_history
- INFO - 2021-05-13 21:37:20,686 - Init Server
- INFO - 2021-05-13 21:37:20,737 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-13 21:37:25,947 - upload_file -> (file_name: map.json)
- INFO - 2021-05-13 21:38:21,423 - Init Server
- INFO - 2021-05-13 21:38:21,435 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-13 21:38:26,459 - upload_file -> (file_name: map.json)
- INFO - 2021-05-13 21:39:50,296 - Init Server
- INFO - 2021-05-13 21:39:50,330 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-13 21:39:56,000 - upload_file -> (file_name: map.json)
- WARNING - 2021-05-13 21:40:41,508 - Unauthorized: /api/user
- WARNING - 2021-05-13 21:40:41,513 - Unauthorized: /api/login_history
- INFO - 2021-05-13 21:40:58,343 - Init Server
- INFO - 2021-05-13 21:40:58,377 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-13 21:41:03,894 - upload_file -> (file_name: map.json)
- WARNING - 2021-05-13 21:42:43,395 - Unauthorized: /api/user
- WARNING - 2021-05-13 21:42:43,403 - Unauthorized: /api/login_history
- INFO - 2021-05-13 21:43:07,700 - Init Server
- INFO - 2021-05-13 21:43:07,728 - file_cache is only supported with oauth2client<4.0.0
- INFO - 2021-05-13 21:43:13,135 - upload_file -> (file_name: map.json)
